// ---------------------------------------------------------------------------
// Chip Registry — Every backend tool as a chip definition
// ---------------------------------------------------------------------------

import type { ChipDef } from './types';
import { PORTS } from '../workflow/port-types';

function fmt(n: number): string {
  if (n >= 1000) return `${n / 1000}k`;
  return String(n);
}

// ---------------------------------------------------------------------------
// FP&A
// ---------------------------------------------------------------------------

const fpaChips: ChipDef[] = [
  {
    id: 'forecast',
    label: 'Forecast',
    domain: 'fpa',
    icon: 'TrendingUp',
    description: 'Run a financial forecast',
    tool: 'fpa_forecast',
    params: [
      { key: 'months', label: 'Months', type: 'months', default: 24, min: 1, max: 60, chipDisplay: (v: number) => `${v}mo` },
      { key: 'method', label: 'Method', type: 'select', default: 'auto', options: [{ label: 'Auto', value: 'auto' }, { label: 'Liquidity Model', value: 'liquidity' }, { label: 'Advanced Regression', value: 'advanced_regression' }, { label: 'Custom Model', value: 'model_construction' }, { label: 'Driver-based', value: 'driver_based' }, { label: 'Seasonal', value: 'seasonal' }, { label: 'Monte Carlo', value: 'monte_carlo' }, { label: 'Regression', value: 'regression' }, { label: 'Budget-based', value: 'budget_pct' }, { label: 'Growth Rate', value: 'growth_rate' }] },
      { key: 'name', label: 'Name', type: 'text', default: '' },
      { key: 'activate', label: 'Save to DB', type: 'select', default: 'false', options: [{ label: 'No', value: 'false' }, { label: 'Yes', value: 'true' }] },
    ],
    inputPorts: [PORTS.driversIn()],
    outputPorts: [PORTS.forecastOut()],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'custom_model',
    label: 'Custom Model',
    domain: 'fpa',
    icon: 'Wand2',
    description: 'Construct a custom forecast model from description',
    tool: 'construct_forecast_model',
    params: [
      { key: 'prompt', label: 'Model Description', type: 'text', default: '' },
      { key: 'months', label: 'Forecast Horizon', type: 'months', default: 24, min: 3, max: 60, chipDisplay: (v: number) => `${v}mo` },
      { key: 'include_events', label: 'Include Events', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No', value: 'false' }] },
      { key: 'include_macro', label: 'Macro Shocks', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No', value: 'false' }] },
      { key: 'persist', label: 'Save to DB', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No (preview)', value: 'false' }] },
    ],
    inputPorts: [PORTS.driversIn()],
    outputPorts: [PORTS.modelOut()],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'execute_model',
    label: 'Execute Model',
    domain: 'fpa',
    icon: 'Play',
    description: 'Execute a constructed forecast model',
    tool: 'execute_forecast_model',
    params: [
      { key: 'model_id', label: 'Model ID', type: 'text', default: '' },
      { key: 'months', label: 'Months', type: 'months', default: 24, min: 1, max: 60 },
    ],
    inputPorts: [PORTS.modelIn()],
    outputPorts: [PORTS.forecastOut()],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
  {
    id: 'pnl',
    label: 'P&L',
    domain: 'fpa',
    icon: 'Receipt',
    description: 'Profit & loss statement',
    tool: 'fpa_pnl',
    params: [
      { key: 'months', label: 'Months', type: 'months', default: 24, min: 1, max: 60 },
      { key: 'view', label: 'View', type: 'select', default: 'waterfall', options: [{ label: 'Waterfall', value: 'waterfall' }, { label: 'Actuals vs Budget', value: 'actuals_vs_budget' }, { label: 'Actuals vs Forecast', value: 'actuals_vs_forecast' }] },
      { key: 'start', label: 'Start (YYYY-MM)', type: 'text', default: '' },
      { key: 'end', label: 'End (YYYY-MM)', type: 'text', default: '' },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.pnlOut()],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'balance_sheet',
    label: 'Balance Sheet',
    domain: 'fpa',
    icon: 'Scale',
    description: 'Balance sheet snapshot',
    tool: 'fpa_balance_sheet',
    params: [
      { key: 'start', label: 'Start (YYYY-MM)', type: 'text', default: '' },
      { key: 'end', label: 'End (YYYY-MM)', type: 'text', default: '' },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.bsOut()],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'cash_flow',
    label: 'Cash Flow',
    domain: 'fpa',
    icon: 'ArrowDownUp',
    description: 'Cash flow statement',
    tool: 'fpa_cash_flow',
    params: [
      { key: 'months', label: 'Months', type: 'months', default: 24, min: 1, max: 60 },
    ],
    inputPorts: [PORTS.driversIn()],
    outputPorts: [PORTS.cashFlowOut()],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'variance',
    label: 'Variance',
    domain: 'fpa',
    icon: 'ArrowLeftRight',
    description: 'Variance analysis (actual vs forecast)',
    tool: 'fpa_variance',
    params: [
      { key: 'budget_id', label: 'Budget ID', type: 'text', default: '' },
      { key: 'start', label: 'Start (YYYY-MM)', type: 'text', default: '' },
      { key: 'end', label: 'End (YYYY-MM)', type: 'text', default: '' },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.varianceOut()],
    outputRenderer: 'delta',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'rolling_forecast',
    label: 'Rolling Forecast',
    domain: 'fpa',
    icon: 'RefreshCw',
    description: 'Rolling 13-week forecast',
    tool: 'fpa_rolling_forecast',
    params: [
      { key: 'weeks', label: 'Weeks', type: 'number', default: 13, min: 4, max: 26 },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.forecastOut()],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'kpi_dashboard',
    label: 'KPI Dashboard',
    domain: 'fpa',
    icon: 'LayoutDashboard',
    description: 'Key performance indicators',
    tool: 'fpa_kpi_dashboard',
    params: [
      { key: 'periods', label: 'Periods', type: 'number', default: 12, min: 1, max: 60 },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.tableOut()],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'unit_economics',
    label: 'Unit Economics',
    domain: 'fpa',
    icon: 'Calculator',
    description: 'LTV, CAC, magic number, payback period',
    tool: 'fpa_computed_metrics',
    params: [
      { key: 'metrics', label: 'Metrics', type: 'select', default: 'all', options: [{ label: 'All', value: 'all' }, { label: 'LTV/CAC', value: 'ltv_cac' }, { label: 'Magic Number', value: 'magic_number' }, { label: 'Rule of 40', value: 'rule_of_40' }, { label: 'CAC Payback', value: 'cac_payback' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.tableOut()],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// Scenario & Stress Testing
// ---------------------------------------------------------------------------

const scenarioChips: ChipDef[] = [
  {
    id: 'scenario',
    label: 'Scenario',
    domain: 'scenario',
    icon: 'GitBranch',
    description: 'Create a scenario branch with driver overrides',
    tool: 'fpa_scenario_create',
    params: [
      { key: 'name', label: 'Name', type: 'text', default: '' },
      { key: 'scenario_description', label: 'Description', type: 'text', default: '' },
      { key: 'probability', label: 'Probability', type: 'percent', default: 50, min: 0, max: 100 },
      { key: 'forecast_months', label: 'Months', type: 'months', default: 24, min: 1, max: 60 },
    ],
    inputPorts: [PORTS.forecastIn(), PORTS.driversIn()],
    outputPorts: [PORTS.scenarioOut()],
    produces: ['scenario_id'],
    outputRenderer: 'tree',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'compare_scenarios',
    label: 'Compare Scenarios',
    domain: 'scenario',
    icon: 'Columns',
    description: 'Side-by-side scenario comparison',
    tool: 'fpa_scenario_compare',
    params: [
      { key: 'forecast_months', label: 'Months', type: 'months', default: 24, min: 6, max: 60 },
    ],
    inputPorts: [PORTS.scenariosIn(true)],
    outputPorts: [PORTS.scenarioSetOut()],
    accepts: ['scenario'],
    outputRenderer: 'delta',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'scenario_tree',
    label: 'Scenario Tree',
    domain: 'scenario',
    icon: 'Network',
    description: 'Visualize the full scenario tree',
    tool: 'run_scenario_tree',
    params: [
      { key: 'depth', label: 'Depth', type: 'number', default: 3, min: 1, max: 5 },
    ],
    inputPorts: [PORTS.scenarioIn()],
    outputPorts: [PORTS.scenarioSetOut()],
    outputRenderer: 'tree',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'stress_test',
    label: 'Stress Test',
    domain: 'scenario',
    icon: 'Zap',
    description: 'Stress test portfolio or scenario',
    tool: 'stress_test_portfolio',
    params: [
      { key: 'shock_type', label: 'Shock', type: 'select', default: 'revenue_drop', options: [{ label: 'Revenue Drop', value: 'revenue_drop' }, { label: 'Cost Spike', value: 'cost_spike' }, { label: 'Churn Increase', value: 'churn_increase' }] },
      { key: 'magnitude', label: 'Magnitude', type: 'percent', default: 30, min: 5, max: 90 },
    ],
    inputPorts: [PORTS.forecastIn(), PORTS.scenarioIn()],
    outputPorts: [PORTS.scenarioOut()],
    accepts: ['scenario', 'macro'],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'bull_bear_base',
    label: 'Bull/Bear/Base',
    domain: 'scenario',
    icon: 'ArrowUpDown',
    description: 'Generate bull, bear, and base case scenarios',
    tool: 'run_bull_bear_base',
    params: [
      { key: 'forecast_months', label: 'Months', type: 'months', default: 24, min: 6, max: 60 },
      { key: 'spread', label: 'Spread %', type: 'percent', default: 30, min: 5, max: 80, chipDisplay: (v: number) => `±${v}%` },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.scenarioSetOut()],
    outputRenderer: 'delta',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'three_way_cash_flow',
    label: 'Three-Way Cash Flow',
    domain: 'scenario',
    icon: 'Split',
    description: 'Cash flow across three scenario paths',
    tool: 'three_scenario_cash_flow',
    params: [
      { key: 'years', label: 'Years', type: 'number', default: 5, min: 1, max: 10 },
    ],
    inputPorts: [PORTS.scenariosIn(true)],
    outputPorts: [PORTS.cashFlowOut()],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 25000,
  },
  {
    id: 'world_model',
    label: 'World Model',
    domain: 'scenario',
    icon: 'Globe2',
    description: 'Multi-factor world model scenario',
    tool: 'world_model_scenario',
    params: [
      { key: 'factors', label: 'Factors', type: 'text', default: '', },
      { key: 'forecast_months', label: 'Months', type: 'months', default: 24, min: 6, max: 60 },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.scenarioOut()],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
];

// ---------------------------------------------------------------------------
// Simulation & Analytics
// ---------------------------------------------------------------------------

const analyticsChips: ChipDef[] = [
  {
    id: 'monte_carlo',
    label: 'Monte Carlo',
    domain: 'analytics',
    icon: 'Dice5',
    description: 'Monte Carlo simulation',
    tool: 'fpa_monte_carlo',
    params: [
      { key: 'iterations', label: 'Iterations', type: 'number', default: 1000, min: 100, max: 50000, step: 100, chipDisplay: (v: number) => fmt(v) },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.monteCarloOut()],
    accepts: ['fpa', 'scenario'],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'sensitivity',
    label: 'Sensitivity',
    domain: 'analytics',
    icon: 'Grid3x3',
    description: 'Sensitivity matrix analysis',
    tool: 'sensitivity_matrix',
    params: [
      { key: 'var_x', label: 'Variable X', type: 'metric', default: 'revenue' },
      { key: 'var_y', label: 'Variable Y', type: 'metric', default: 'revenue_multiple' },
      { key: 'range_x', label: 'Range X (comma-sep)', type: 'text', default: '' },
      { key: 'range_y', label: 'Range Y (comma-sep)', type: 'text', default: '' },
    ],
    inputPorts: [PORTS.valuationIn()],
    outputPorts: [PORTS.sensitivityOut()],
    outputRenderer: 'matrix',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'regression',
    label: 'Regression',
    domain: 'analytics',
    icon: 'LineChart',
    description: 'Regression analysis',
    tool: 'fpa_regression',
    params: [
      { key: 'method', label: 'Method', type: 'select', default: 'linear', options: [{ label: 'Linear', value: 'linear' }, { label: 'Polynomial', value: 'poly' }, { label: 'LOESS', value: 'loess' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.chartOut()],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'seasonality',
    label: 'Seasonality',
    domain: 'analytics',
    icon: 'CalendarDays',
    description: 'Detect seasonal patterns',
    tool: 'fpa_detect_seasonality',
    params: [
      { key: 'metric', label: 'Metric', type: 'select', default: 'revenue', options: [{ label: 'Revenue', value: 'revenue' }, { label: 'COGS', value: 'cogs' }, { label: 'Headcount', value: 'headcount' }, { label: 'Burn Rate', value: 'burn_rate' }, { label: 'New Customers', value: 'new_customers' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.chartOut()],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'correlation',
    label: 'Correlation',
    domain: 'analytics',
    icon: 'Link2',
    description: 'Correlate actuals between metrics',
    tool: 'fpa_correlate_actuals',
    params: [
      { key: 'metric_a', label: 'Metric A', type: 'metric', default: 'revenue' },
      { key: 'metric_b', label: 'Metric B', type: 'metric', default: 'headcount' },
      { key: 'method', label: 'Method', type: 'select', default: 'pearson', options: [{ label: 'Pearson', value: 'pearson' }, { label: 'Spearman', value: 'spearman' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.chartOut()],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'driver_impact',
    label: 'Driver Impact',
    domain: 'analytics',
    icon: 'BarChart3',
    description: 'Driver impact ranking (tornado chart)',
    tool: 'fpa_driver_impact_ranking',
    params: [
      { key: 'target_metric', label: 'Target', type: 'select', default: 'runway_months', options: [{ label: 'Runway', value: 'runway_months' }, { label: 'EBITDA', value: 'ebitda' }, { label: 'Cash Balance', value: 'cash_balance' }, { label: 'Revenue', value: 'revenue' }] },
      { key: 'perturbation', label: 'Perturbation %', type: 'percent', default: 10, min: 1, max: 50 },
      { key: 'forecast_months', label: 'Months', type: 'months', default: 12, min: 1, max: 36 },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.chartOut()],
    outputRenderer: 'tornado',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'trace_impact',
    label: 'Trace Impact',
    domain: 'analytics',
    icon: 'Workflow',
    description: 'Trace strategic impact from a source driver',
    tool: 'fpa_trace_strategic_impact',
    params: [
      { key: 'source_driver', label: 'Driver', type: 'text', default: '' },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.chartOut()],
    outputRenderer: 'sankey',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'ripple_propagation',
    label: 'Ripple Propagation',
    domain: 'analytics',
    icon: 'Waves',
    description: 'Propagate a driver change through all downstream metrics — shows full impact chain',
    tool: 'fpa_driver_impact_ranking',
    kind: 'tool',
    params: [
      { key: 'driver_id', label: 'Driver', type: 'select', default: 'revenue_growth', options: [
        { label: 'Revenue Growth', value: 'revenue_growth' },
        { label: 'Gross Margin', value: 'gross_margin' },
        { label: 'Burn Rate', value: 'burn_rate' },
        { label: 'Headcount', value: 'headcount' },
        { label: 'Churn Rate', value: 'churn_rate' },
        { label: 'ACV', value: 'acv' },
        { label: 'NRR', value: 'nrr' },
        { label: 'CAC', value: 'cac' },
        { label: 'Pricing', value: 'pricing' },
      ] },
      { key: 'delta_pct', label: 'Change %', type: 'percent', default: 10, min: -50, max: 50, chipDisplay: (v: number) => `${v > 0 ? '+' : ''}${v}%` },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.chartOut()],
    outputRenderer: 'sankey',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
];

// ---------------------------------------------------------------------------
// Valuation & Cap Table
// ---------------------------------------------------------------------------

const capitalChips: ChipDef[] = [
  {
    id: 'valuation',
    label: 'Valuation',
    domain: 'capital',
    icon: 'DollarSign',
    description: 'Run a valuation (PWERM, DCF, OPM, comps)',
    tool: 'run_valuation',
    params: [
      { key: 'method', label: 'Method', type: 'select', default: 'auto', options: [{ label: 'Auto', value: 'auto' }, { label: 'DCF', value: 'dcf' }, { label: 'PWERM', value: 'pwerm' }, { label: 'OPM', value: 'opm' }, { label: 'Comparables', value: 'comparable' }, { label: 'Revenue Multiple', value: 'revenue_multiple' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.valuationOut()],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'dcf',
    label: 'DCF',
    domain: 'capital',
    icon: 'Calculator',
    description: 'Discounted cash flow valuation',
    tool: 'run_valuation',
    params: [
      { key: 'method', label: 'Method', type: 'text', default: 'dcf' },
      { key: 'discount_rate', label: 'Discount Rate', type: 'percent', default: 15, min: 1, max: 50 },
      { key: 'terminal_growth', label: 'Terminal Growth', type: 'percent', default: 3, min: 0, max: 10 },
      { key: 'projection_years', label: 'Years', type: 'number', default: 5, min: 1, max: 10 },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.valuationOut()],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'comparables',
    label: 'Comparables',
    domain: 'capital',
    icon: 'Users',
    description: 'Comparable company analysis',
    tool: 'run_valuation',
    params: [
      { key: 'method', label: 'Method', type: 'text', default: 'comparable' },
      { key: 'peer_count', label: 'Peer Count', type: 'number', default: 5, min: 3, max: 20 },
      { key: 'multiple_type', label: 'Multiple', type: 'select', default: 'revenue', options: [{ label: 'Revenue', value: 'revenue' }, { label: 'EBITDA', value: 'ebitda' }, { label: 'ARR', value: 'arr' }, { label: 'Gross Profit', value: 'gross_profit' }] },
      { key: 'geography', label: 'Geography', type: 'select', default: 'any', options: [{ label: 'Any', value: 'any' }, { label: 'US', value: 'us' }, { label: 'Europe', value: 'eu' }, { label: 'Global', value: 'global' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.valuationOut()],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'cap_table',
    label: 'Cap Table',
    domain: 'capital',
    icon: 'PieChart',
    description: 'Cap table evolution (Sankey visualization)',
    tool: 'cap_table_evolution',
    params: [
      { key: 'include_sankey', label: 'Include Sankey', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No', value: 'false' }] },
    ],
    inputPorts: [PORTS.dataIn()],
    outputPorts: [PORTS.capTableOut()],
    outputRenderer: 'sankey',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'liquidation_waterfall',
    label: 'Liquidation Waterfall',
    domain: 'capital',
    icon: 'Droplets',
    description: 'Liquidation waterfall analysis',
    tool: 'liquidation_waterfall',
    params: [
      { key: 'exit_value', label: 'Exit Value', type: 'currency', default: 10000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'exit_type', label: 'Exit Type', type: 'select', default: 'strategic_ma', options: [{ label: 'Strategic M&A', value: 'strategic_ma' }, { label: 'IPO', value: 'ipo' }, { label: 'Acqui-hire', value: 'acquihire' }, { label: 'Wind Down', value: 'wind_down' }] },
    ],
    inputPorts: [PORTS.capTableIn()],
    outputPorts: [PORTS.waterfallOut()],
    outputRenderer: 'waterfall',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'anti_dilution',
    label: 'Anti-Dilution',
    domain: 'capital',
    icon: 'ShieldCheck',
    description: 'Anti-dilution modeling',
    tool: 'anti_dilution_modeling',
    params: [
      { key: 'ratchet_type', label: 'Ratchet', type: 'select', default: 'broad_weighted', options: [{ label: 'Full Ratchet', value: 'full_ratchet' }, { label: 'Broad Weighted', value: 'broad_weighted' }, { label: 'Narrow Weighted', value: 'narrow_weighted' }] },
    ],
    inputPorts: [PORTS.capTableIn()],
    outputPorts: [PORTS.capTableOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'debt_conversion',
    label: 'Debt Conversion',
    domain: 'capital',
    icon: 'ArrowRightLeft',
    description: 'Debt conversion modeling',
    tool: 'debt_conversion_modeling',
    params: [
      { key: 'trigger', label: 'Trigger', type: 'select', default: 'qualified_financing', options: [{ label: 'Qualified Financing', value: 'qualified_financing' }, { label: 'Maturity', value: 'maturity' }, { label: 'M&A', value: 'ma' }, { label: 'IPO', value: 'ipo' }] },
    ],
    inputPorts: [PORTS.capTableIn()],
    outputPorts: [PORTS.capTableOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'funding_round',
    label: 'Funding Round',
    domain: 'capital',
    icon: 'CircleDollarSign',
    description: 'Model a funding round',
    tool: 'cap_table_evolution',
    kind: 'tool',
    params: [
      { key: 'round_name', label: 'Round', type: 'select', default: 'series_a', options: [{ label: 'Pre-Seed', value: 'pre_seed' }, { label: 'Seed', value: 'seed' }, { label: 'Series A', value: 'series_a' }, { label: 'Series B', value: 'series_b' }, { label: 'Series C+', value: 'series_c' }] },
      { key: 'amount', label: 'Amount', type: 'currency', default: 5000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'pre_money', label: 'Pre-Money', type: 'currency', default: 20000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
    ],
    inputPorts: [PORTS.capTableIn()],
    outputPorts: [PORTS.capTableOut()],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'exit_model',
    label: 'Exit Model',
    domain: 'capital',
    icon: 'LogOut',
    description: 'Model exit scenarios',
    tool: 'run_scenario',
    kind: 'tool',
    params: [
      { key: 'scenario_type', label: 'Type', type: 'text', default: 'exit' },
      { key: 'exit_type', label: 'Exit Type', type: 'select', default: 'strategic_ma', options: [{ label: 'Strategic M&A', value: 'strategic_ma' }, { label: 'IPO', value: 'ipo' }, { label: 'Secondary Sale', value: 'secondary' }, { label: 'Acqui-hire', value: 'acquihire' }, { label: 'Wind Down', value: 'wind_down' }] },
      { key: 'exit_value', label: 'Exit Value', type: 'currency', default: 50000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'exit_year', label: 'Exit Year', type: 'number', default: 2028, min: 2025, max: 2035 },
      { key: 'probability', label: 'Probability', type: 'percent', default: 50, min: 0, max: 100 },
    ],
    inputPorts: [PORTS.valuationIn(), PORTS.capTableIn()],
    outputPorts: [PORTS.scenarioOut()],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'round_model',
    label: 'Round Model',
    domain: 'capital',
    icon: 'Coins',
    description: 'Model round mechanics',
    tool: 'cap_table_evolution',
    kind: 'tool',
    params: [
      { key: 'round_type', label: 'Round Type', type: 'select', default: 'priced', options: [{ label: 'Priced Round', value: 'priced' }, { label: 'SAFE', value: 'safe' }, { label: 'Convertible Note', value: 'convertible' }, { label: 'Bridge', value: 'bridge' }] },
      { key: 'target_raise', label: 'Target Raise', type: 'currency', default: 5000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'option_pool_increase', label: 'Option Pool %', type: 'percent', default: 10, min: 0, max: 30 },
      { key: 'force_recalculate', label: 'Recalculate', type: 'select', default: 'false', options: [{ label: 'No (cached)', value: 'false' }, { label: 'Yes', value: 'true' }] },
    ],
    inputPorts: [PORTS.capTableIn()],
    outputPorts: [PORTS.capTableOut()],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'cascade_simulation',
    label: 'Cascade Simulation',
    domain: 'capital',
    icon: 'Layers',
    description: 'Simulate cascading effects of legal instrument changes — anti-dilution repricing, covenant breaches, conversion triggers',
    tool: 'cascade_engine',
    kind: 'tool',
    params: [
      { key: 'trigger_type', label: 'Trigger', type: 'select', default: 'dilution', options: [
        { label: 'Dilution Event', value: 'dilution' },
        { label: 'Anti-Dilution', value: 'anti_dilution' },
        { label: 'Drag-Along', value: 'drag_along' },
        { label: 'Liquidation Preference', value: 'liquidation_pref' },
        { label: 'Conversion Trigger', value: 'conversion' },
        { label: 'Covenant Default', value: 'covenant_default' },
      ] },
      { key: 'trigger_value', label: 'Trigger Value', type: 'currency', default: 0, chipDisplay: (v: number) => v ? `$${(v / 1e6).toFixed(1)}M` : '' },
    ],
    inputPorts: [PORTS.capTableIn()],
    outputPorts: [{ id: 'cascade_result', label: 'Cascade Result', dataType: 'table' as any, direction: 'out' as const, required: false, multi: false }],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
];

// ---------------------------------------------------------------------------
// Funding & Capital
// ---------------------------------------------------------------------------

const fundingChips: ChipDef[] = [
  {
    id: 'equity_raise',
    label: 'Equity Raise',
    domain: 'funding',
    icon: 'TrendingUp',
    description: 'Model an equity raise',
    tool: 'funding_injection',
    params: [
      { key: 'amount', label: 'Amount', type: 'currency', default: 5000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'pre_money', label: 'Pre-Money', type: 'currency', default: 20000000 },
      { key: 'round_name', label: 'Round', type: 'text', default: '' },
    ],
    inputPorts: [PORTS.capTableIn(), PORTS.forecastIn()],
    outputPorts: [PORTS.capTableOut(), PORTS.forecastOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'debt',
    label: 'Debt',
    domain: 'funding',
    icon: 'Banknote',
    description: 'Model a debt raise',
    tool: 'funding_injection',
    params: [
      { key: 'amount', label: 'Principal', type: 'currency', default: 2000000 },
      { key: 'interest_rate', label: 'Rate %', type: 'percent', default: 8, min: 0, max: 30 },
      { key: 'term_months', label: 'Term', type: 'months', default: 36, min: 1, max: 120 },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.forecastOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'safe',
    label: 'SAFE',
    domain: 'funding',
    icon: 'FileCheck',
    description: 'Model a SAFE note',
    tool: 'funding_injection',
    params: [
      { key: 'amount', label: 'Amount', type: 'currency', default: 1000000 },
      { key: 'valuation_cap', label: 'Val Cap', type: 'currency', default: 10000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M cap` },
      { key: 'discount', label: 'Discount %', type: 'percent', default: 20, min: 0, max: 50 },
    ],
    inputPorts: [PORTS.capTableIn()],
    outputPorts: [PORTS.capTableOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'venture_debt',
    label: 'Venture Debt',
    domain: 'funding',
    icon: 'Landmark',
    description: 'Model venture debt',
    tool: 'funding_injection',
    params: [
      { key: 'amount', label: 'Amount', type: 'currency', default: 3000000 },
      { key: 'interest_rate', label: 'Rate %', type: 'percent', default: 12, min: 0, max: 30 },
      { key: 'type', label: 'Type', type: 'text', default: 'venture_debt' },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.forecastOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'convertible',
    label: 'Convertible',
    domain: 'funding',
    icon: 'Repeat',
    description: 'Model convertible debt',
    tool: 'funding_injection',
    params: [
      { key: 'amount', label: 'Amount', type: 'currency', default: 2000000 },
      { key: 'cap', label: 'Val Cap', type: 'currency', default: 10000000 },
      { key: 'discount', label: 'Discount %', type: 'percent', default: 20, min: 0, max: 50 },
      { key: 'coupon', label: 'Coupon %', type: 'percent', default: 5, min: 0, max: 15 },
    ],
    inputPorts: [PORTS.capTableIn()],
    outputPorts: [PORTS.capTableOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// Macro Events
// ---------------------------------------------------------------------------

const macroChips: ChipDef[] = [
  {
    id: 'recession',
    label: 'Recession',
    domain: 'macro',
    icon: 'TrendingDown',
    description: 'Model a recession event',
    tool: 'analyse_macro_event',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.scenarioOut()],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'rate_hike',
    label: 'Rate Hike',
    domain: 'macro',
    icon: 'ArrowUpRight',
    description: 'Model an interest rate hike',
    tool: 'apply_macro_shock',
    params: [
      { key: 'basis_points', label: 'Basis Points', type: 'number', default: 100, min: 25, max: 500, step: 25, chipDisplay: (v: number) => `${v}bps` },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.scenarioOut()],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'market_crash',
    label: 'Market Crash',
    domain: 'macro',
    icon: 'AlertTriangle',
    description: 'Model a market crash',
    tool: 'apply_macro_shock',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.scenarioOut()],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'trade_war',
    label: 'Trade War',
    domain: 'macro',
    icon: 'Swords',
    description: 'Model trade war impact',
    tool: 'apply_macro_shock',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.scenarioOut()],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'supply_chain_shock',
    label: 'Supply Chain Shock',
    domain: 'macro',
    icon: 'Truck',
    description: 'Model supply chain disruption',
    tool: 'apply_macro_shock',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.scenarioOut()],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'pandemic',
    label: 'Pandemic',
    domain: 'macro',
    icon: 'Bug',
    description: 'Model pandemic impact',
    tool: 'apply_macro_shock',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    inputPorts: [PORTS.forecastIn()],
    outputPorts: [PORTS.scenarioOut()],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
];

// ---------------------------------------------------------------------------
// Company Intelligence
// ---------------------------------------------------------------------------

const intelChips: ChipDef[] = [
  {
    id: 'source_companies',
    label: 'Source Companies',
    domain: 'intel',
    icon: 'Search',
    description: 'Source companies by criteria',
    tool: 'source_companies',
    params: [
      { key: 'sector', label: 'Sector', type: 'text', default: '' },
      { key: 'stage', label: 'Stage', type: 'select', default: '', options: [{ label: 'Pre-Seed', value: 'pre-seed' }, { label: 'Seed', value: 'seed' }, { label: 'Series A', value: 'series_a' }, { label: 'Series B', value: 'series_b' }, { label: 'Growth', value: 'growth' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'enrich',
    label: 'Enrich',
    domain: 'intel',
    icon: 'Sparkles',
    description: 'Enrich company data',
    tool: 'enrich_company_proactive',
    params: [
      { key: 'company_name', label: 'Company', type: 'text', default: '' },
      { key: 'push_to_grid', label: 'Add to Portfolio', type: 'select', default: 'false', options: [{ label: 'No', value: 'false' }, { label: 'Yes', value: 'true' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'competitive_intel',
    label: 'Competitive Intel',
    domain: 'intel',
    icon: 'Target',
    description: 'Competitive intelligence analysis',
    tool: 'run_skill',
    params: [
      { key: 'skill_name', label: 'Skill', type: 'text', default: 'competitive-intelligence' },
      { key: 'focus', label: 'Focus', type: 'select', default: 'full', options: [{ label: 'Full Landscape', value: 'full' }, { label: 'Direct Competitors', value: 'direct' }, { label: 'Market Share', value: 'market_share' }, { label: 'Pricing Analysis', value: 'pricing' }, { label: 'Feature Comparison', value: 'features' }] },
      { key: 'depth', label: 'Depth', type: 'select', default: 'standard', options: [{ label: 'Quick Scan', value: 'quick' }, { label: 'Standard', value: 'standard' }, { label: 'Deep Dive', value: 'deep' }] },
    ],
    outputRenderer: 'narrative',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
  {
    id: 'market_research',
    label: 'Market Research',
    domain: 'intel',
    icon: 'BookOpen',
    description: 'Market research and sizing',
    tool: 'web_search',
    params: [
      { key: 'sector', label: 'Sector', type: 'text', default: '' },
      { key: 'focus', label: 'Focus', type: 'select', default: 'tam_sam_som', options: [{ label: 'TAM/SAM/SOM', value: 'tam_sam_som' }, { label: 'Growth Trends', value: 'growth_trends' }, { label: 'Competitive Landscape', value: 'competitive' }, { label: 'Regulatory', value: 'regulatory' }, { label: 'Full Report', value: 'full' }] },
      { key: 'geography', label: 'Geography', type: 'select', default: 'global', options: [{ label: 'Global', value: 'global' }, { label: 'US', value: 'us' }, { label: 'Europe', value: 'eu' }, { label: 'APAC', value: 'apac' }] },
    ],
    outputRenderer: 'narrative',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
  {
    id: 'diligence',
    label: 'Diligence',
    domain: 'intel',
    icon: 'ClipboardCheck',
    description: 'Lightweight due diligence',
    tool: 'lightweight_diligence',
    params: [
      { key: 'company_name', label: 'Company', type: 'text', default: '' },
    ],
    outputRenderer: 'narrative',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
  // team_comparison removed — no backend implementation
  {
    id: 'web_search',
    label: 'Web Search',
    domain: 'intel',
    icon: 'Globe',
    description: 'Search the web for intelligence',
    tool: 'web_search',
    kind: 'tool',
    params: [
      { key: 'query', label: 'Search Query', type: 'text', default: '' },
      { key: 'search_depth', label: 'Depth', type: 'select', default: 'basic', options: [{ label: 'Basic', value: 'basic' }, { label: 'Advanced', value: 'advanced' }] },
    ],
    outputRenderer: 'narrative',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
  {
    id: 'search_db',
    label: 'Search DB',
    domain: 'intel',
    icon: 'Database',
    description: 'Search the database',
    tool: 'search_companies_db',
    kind: 'tool',
    params: [
      { key: 'query', label: 'Query', type: 'text', default: '' },
      { key: 'limit', label: 'Max Results', type: 'number', default: 10, min: 1, max: 100 },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'parse_accounts',
    label: 'Parse Accounts',
    domain: 'intel',
    icon: 'FileSpreadsheet',
    description: 'Parse financial accounts',
    tool: 'parse_accounts',
    kind: 'tool',
    params: [
      { key: 'format', label: 'Format', type: 'select', default: 'auto', options: [{ label: 'Auto-detect', value: 'auto' }, { label: 'PDF', value: 'pdf' }, { label: 'Excel', value: 'xlsx' }, { label: 'Text', value: 'txt' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
  {
    id: 'build_company_list',
    label: 'Build Company List',
    domain: 'intel',
    icon: 'ListPlus',
    description: 'Build a company list from criteria',
    tool: 'build_company_list',
    kind: 'tool',
    params: [
      { key: 'criteria', label: 'Criteria', type: 'text', default: '' },
      { key: 'sector', label: 'Sector', type: 'text', default: '' },
      { key: 'stage', label: 'Stage', type: 'select', default: '', options: [{ label: 'Any', value: '' }, { label: 'Pre-Seed', value: 'pre-seed' }, { label: 'Seed', value: 'seed' }, { label: 'Series A', value: 'series_a' }, { label: 'Series B', value: 'series_b' }, { label: 'Growth', value: 'growth' }] },
      { key: 'geography', label: 'Geography', type: 'select', default: '', options: [{ label: 'Any', value: '' }, { label: 'US', value: 'us' }, { label: 'Europe', value: 'eu' }, { label: 'UK', value: 'uk' }, { label: 'APAC', value: 'apac' }, { label: 'LATAM', value: 'latam' }] },
      { key: 'max_results', label: 'Max Results', type: 'number', default: 10, min: 1, max: 20 },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
];

// ---------------------------------------------------------------------------
// Documents & Reporting
// ---------------------------------------------------------------------------

const reportChips: ChipDef[] = [
  {
    id: 'generate_deck',
    label: 'Generate Deck',
    domain: 'report',
    icon: 'Presentation',
    description: 'Generate a presentation deck',
    tool: 'generate_deck',
    params: [
      { key: 'template', label: 'Template', type: 'select', default: 'pitch', options: [{ label: 'Pitch Deck', value: 'pitch' }, { label: 'Board Update', value: 'board' }, { label: 'Investor Update', value: 'investor' }, { label: 'Data Room', value: 'data_room' }] },
    ],
    accepts: ['fpa', 'scenario', 'analytics', 'capital'],
    outputRenderer: 'deck',
    costTier: 'expensive',
    timeoutMs: 60000,
  },
  {
    id: 'write_memo',
    label: 'Write Memo',
    domain: 'report',
    icon: 'FileText',
    description: 'Write to investment memo',
    tool: 'write_to_memo',
    params: [
      { key: 'section', label: 'Section', type: 'text', default: '' },
    ],
    outputRenderer: 'memo-section',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
  // Old generic chart chip removed — replaced by chart domain chips
  {
    id: 'search_docs',
    label: 'Search Docs',
    domain: 'report',
    icon: 'FileSearch',
    description: 'Search across uploaded documents',
    tool: 'search_across_documents',
    params: [
      { key: 'query', label: 'Query', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'draft_contract',
    label: 'Draft Contract',
    domain: 'report',
    icon: 'FileSignature',
    description: 'Draft a legal contract',
    tool: 'draft_contract',
    params: [
      { key: 'type', label: 'Type', type: 'select', default: 'nda', options: [{ label: 'NDA', value: 'nda' }, { label: 'SHA', value: 'sha' }, { label: 'SPA', value: 'spa' }, { label: 'Term Sheet', value: 'term_sheet' }] },
    ],
    outputRenderer: 'document',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  // lp_query_response removed — no backend implementation
];

// ---------------------------------------------------------------------------
// Compliance & Legal
// ---------------------------------------------------------------------------

const complianceChips: ChipDef[] = [
  // kyc/check and aml/screen removed — no backend implementation
  {
    id: 'transfer_pricing',
    label: 'Transfer Pricing',
    domain: 'compliance',
    icon: 'ArrowLeftRight',
    description: 'Transfer pricing analysis',
    tool: 'tp_analyze_transaction',
    params: [
      { key: 'force_method', label: 'Method', type: 'select', default: 'auto', options: [{ label: 'Auto-detect', value: 'auto' }, { label: 'CUP', value: 'cup' }, { label: 'Resale Price', value: 'resale' }, { label: 'Cost Plus', value: 'cost_plus' }, { label: 'Profit Split', value: 'profit_split' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'far_analysis',
    label: 'FAR Analysis',
    domain: 'compliance',
    icon: 'BookOpenCheck',
    description: 'Functions, assets, risks analysis',
    tool: 'tp_far_analysis',
    params: [
      { key: 'entity', label: 'Entity', type: 'text', default: '' },
      { key: 'focus', label: 'Focus', type: 'select', default: 'all', options: [{ label: 'All', value: 'all' }, { label: 'Functions', value: 'functions' }, { label: 'Assets', value: 'assets' }, { label: 'Risks', value: 'risks' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'tp_report',
    label: 'TP Report',
    domain: 'compliance',
    icon: 'FileSpreadsheet',
    description: 'Transfer pricing report generation',
    tool: 'tp_generate_report',
    params: [
      { key: 'jurisdiction', label: 'Jurisdiction', type: 'select', default: 'oecd', options: [{ label: 'OECD', value: 'oecd' }, { label: 'US (IRC 482)', value: 'us' }, { label: 'UK', value: 'uk' }, { label: 'EU', value: 'eu' }] },
      { key: 'fiscal_year', label: 'Fiscal Year', type: 'number', default: new Date().getFullYear(), min: 2020, max: 2030 },
    ],
    outputRenderer: 'document',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
  {
    id: 'contract_impact',
    label: 'Contract Impact',
    domain: 'compliance',
    icon: 'FileWarning',
    description: 'Contract P&L attribution',
    tool: 'contract_pnl_attribution',
    params: [
      { key: 'period', label: 'Period', type: 'select', default: 'current', options: [{ label: 'Current', value: 'current' }, { label: 'YTD', value: 'ytd' }, { label: 'Last 12 Months', value: 'ltm' }, { label: 'Full Term', value: 'full' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'contract_analysis',
    label: 'Analyze Contract',
    domain: 'compliance',
    icon: 'FileSearch',
    description: 'Extract and analyze key terms, obligations, and risks from a contract document',
    tool: 'legal_brain',
    kind: 'tool',
    params: [
      { key: 'document_id', label: 'Document ID', type: 'text', default: '' },
      { key: 'analysis_type', label: 'Analysis', type: 'select', default: 'full', options: [
        { label: 'Full Analysis', value: 'full' },
        { label: 'Key Terms', value: 'key_terms' },
        { label: 'Risk Assessment', value: 'risk' },
        { label: 'Obligations', value: 'obligations' },
      ] },
    ],
    outputRenderer: 'narrative',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
  {
    id: 'redline_analysis',
    label: 'Redline Analysis',
    domain: 'compliance',
    icon: 'PenLine',
    description: 'Analyze financial impact of clause changes — redline a term and see P&L/cap table effects',
    tool: 'redline_impact',
    kind: 'tool',
    params: [
      { key: 'clause_type', label: 'Clause Type', type: 'select', default: 'liquidation_preference', options: [
        { label: 'Liquidation Preference', value: 'liquidation_preference' },
        { label: 'Anti-Dilution', value: 'anti_dilution' },
        { label: 'Vesting Schedule', value: 'vesting' },
        { label: 'Conversion Rights', value: 'conversion' },
        { label: 'Drag-Along', value: 'drag_along' },
        { label: 'Tag-Along', value: 'tag_along' },
        { label: 'Board Composition', value: 'board' },
        { label: 'Covenant', value: 'covenant' },
      ] },
      { key: 'original_value', label: 'Original', type: 'text', default: '' },
      { key: 'new_value', label: 'Proposed', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'legal_signals',
    label: 'Legal Signal Detector',
    domain: 'compliance',
    icon: 'AlertTriangle',
    description: 'Detect legal signals and risk indicators across uploaded documents',
    tool: 'legal_signal_detector',
    kind: 'tool',
    params: [
      { key: 'signal_type', label: 'Signal Type', type: 'select', default: 'all', options: [{ label: 'All', value: 'all' }, { label: 'IP Risk', value: 'ip' }, { label: 'Liability', value: 'liability' }, { label: 'Regulatory', value: 'regulatory' }, { label: 'Change of Control', value: 'change_of_control' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'clause_diff',
    label: 'Compare Clauses',
    domain: 'compliance',
    icon: 'GitCompare',
    description: 'Diff two versions of a clause and analyze the financial and legal impact of changes',
    tool: 'clause_diff',
    kind: 'tool',
    params: [
      { key: 'clause_a', label: 'Clause A', type: 'text', default: '' },
      { key: 'clause_b', label: 'Clause B', type: 'text', default: '' },
    ],
    outputRenderer: 'narrative',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
];

// ---------------------------------------------------------------------------
// Portfolio Operations
// ---------------------------------------------------------------------------

const portfolioChips: ChipDef[] = [
  {
    id: 'bulk_valuation',
    label: 'Bulk Valuation',
    domain: 'portfolio',
    icon: 'Layers',
    description: 'Valuate entire portfolio',
    tool: 'bulk_operation',
    params: [
      { key: 'operation', label: 'Operation', type: 'text', default: 'valuation' },
      { key: 'method', label: 'Method', type: 'select', default: 'auto', options: [{ label: 'Auto', value: 'auto' }, { label: 'Revenue Multiple', value: 'revenue_multiple' }, { label: 'DCF', value: 'dcf' }, { label: 'Last Round', value: 'last_round' }] },
      { key: 'as_of_date', label: 'As of Date', type: 'text', default: '' },
      { key: 'include_markdowns', label: 'Include Markdowns', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No', value: 'false' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 60000,
  },
  {
    id: 'portfolio_monte_carlo',
    label: 'Portfolio Monte Carlo',
    domain: 'portfolio',
    icon: 'Dice5',
    description: 'Monte Carlo across portfolio',
    tool: 'monte_carlo_portfolio',
    params: [
      { key: 'iterations', label: 'Iterations', type: 'number', default: 10000, min: 100, max: 100000, step: 1000, chipDisplay: (v: number) => fmt(v) },
    ],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 60000,
  },
  // portfolio_pacing and portfolio_graduation removed — no backend implementation
  {
    id: 'fx_impact',
    label: 'FX Impact',
    domain: 'portfolio',
    icon: 'Coins',
    description: 'Foreign exchange impact on portfolio',
    tool: 'fx_portfolio_impact',
    params: [
      { key: 'base_currency', label: 'Base Currency', type: 'select', default: 'USD', options: [{ label: 'USD', value: 'USD' }, { label: 'EUR', value: 'EUR' }, { label: 'GBP', value: 'GBP' }, { label: 'CHF', value: 'CHF' }, { label: 'JPY', value: 'JPY' }] },
      { key: 'shock_pct', label: 'Shock %', type: 'percent', default: 10, min: 1, max: 50 },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'batch_enrich',
    label: 'Batch Enrich',
    domain: 'portfolio',
    icon: 'Sparkles',
    description: 'Batch enrich portfolio companies',
    tool: 'batch_enrich',
    params: [
      { key: 'fields', label: 'Fields', type: 'select', default: 'all', options: [{ label: 'All Gaps', value: 'all' }, { label: 'Revenue', value: 'arr' }, { label: 'Valuation', value: 'valuation' }, { label: 'Team', value: 'team_size' }, { label: 'Funding', value: 'funding' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 60000,
  },
];

// ---------------------------------------------------------------------------
// Communications
// ---------------------------------------------------------------------------

const commsChips: ChipDef[] = [
  {
    id: 'email',
    label: 'Email',
    domain: 'comms',
    icon: 'Mail',
    description: 'Send an email',
    tool: 'send_email',
    params: [
      { key: 'recipients', label: 'To', type: 'text', default: '' },
    ],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'slack',
    label: 'Slack',
    domain: 'comms',
    icon: 'MessageSquare',
    description: 'Send a Slack message',
    tool: 'send_slack',
    params: [
      { key: 'channel', label: 'Channel', type: 'text', default: '' },
    ],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// Data & Grid
// ---------------------------------------------------------------------------

const dataChips: ChipDef[] = [
  {
    id: 'query_grid',
    label: 'Query Grid',
    domain: 'data',
    icon: 'Table2',
    description: 'Query the data grid',
    tool: 'query_grid',
    params: [
      { key: 'query', label: 'Query', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'search_grid',
    label: 'Search Grid',
    domain: 'data',
    icon: 'Search',
    description: 'Search grid with conditions',
    tool: 'search_grid',
    params: [
      { key: 'query', label: 'Search', type: 'text', default: '' },
      { key: 'column', label: 'Column', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'read_financials',
    label: 'Read Financials',
    domain: 'data',
    icon: 'FileSpreadsheet',
    description: 'Read company financials',
    tool: 'read_financials',
    params: [
      { key: 'statement_type', label: 'Statement', type: 'select', default: 'income', options: [{ label: 'Income', value: 'income' }, { label: 'Balance Sheet', value: 'balance_sheet' }, { label: 'Cash Flow', value: 'cash_flow' }] },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'xero_sync',
    label: 'Xero Sync',
    domain: 'data',
    icon: 'RefreshCcw',
    description: 'Sync data from Xero',
    tool: 'fpa_xero_sync',
    params: [
      { key: 'sync_type', label: 'Sync', type: 'select', default: 'full', options: [{ label: 'Full Sync', value: 'full' }, { label: 'Incremental', value: 'incremental' }] },
    ],
    outputRenderer: 'notification',
    costTier: 'cheap',
    timeoutMs: 30000,
  },
  {
    id: 'upload_actuals',
    label: 'Upload Actuals',
    domain: 'data',
    icon: 'Upload',
    description: 'Upload actual financial data',
    tool: 'fpa_upload_actuals',
    params: [
      { key: 'source', label: 'Source', type: 'select', default: 'manual', options: [{ label: 'Manual Entry', value: 'manual' }, { label: 'CSV Upload', value: 'csv' }, { label: 'From Document', value: 'document' }] },
    ],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 15000,
  },
  {
    id: 'ingest_docs',
    label: 'Ingest Docs',
    domain: 'data',
    icon: 'FolderInput',
    description: 'Ingest documents into the system',
    tool: 'ingest_documents',
    kind: 'tool',
    params: [
      { key: 'extraction_focus', label: 'Focus', type: 'text', default: '' },
    ],
    outputRenderer: 'notification',
    costTier: 'cheap',
    timeoutMs: 30000,
  },
  {
    id: 'bulk_write',
    label: 'Bulk Write',
    domain: 'data',
    icon: 'FileOutput',
    description: 'Bulk write to data grid',
    tool: 'bulk_write_grid',
    kind: 'tool',
    params: [
      { key: 'source', label: 'Source', type: 'select', default: 'upstream', options: [{ label: 'From Upstream', value: 'upstream' }, { label: 'Agent Write', value: 'agent_write' }] },
    ],
    outputRenderer: 'notification',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'analyze_financials',
    label: 'Analyze Financials',
    domain: 'data',
    icon: 'BarChart3',
    description: 'Analyze financial statements',
    tool: 'analyze_financials',
    kind: 'tool',
    params: [
      { key: 'metrics', label: 'Metrics', type: 'select', default: 'all', options: [{ label: 'All', value: 'all' }, { label: 'Margins', value: 'margins' }, { label: 'Growth', value: 'growth' }, { label: 'Efficiency', value: 'efficiency' }] },
      { key: 'from_date', label: 'From (YYYY-MM)', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
];

// ---------------------------------------------------------------------------
// V2: Modeling Domain
// ---------------------------------------------------------------------------

const modelingChips: ChipDef[] = [
  {
    id: 'pnl_cascade',
    label: 'P&L Cascade',
    domain: 'modeling',
    icon: 'Layers',
    description: 'Full P&L cascade with department breakdowns',
    tool: 'run_cash_flow_model',
    kind: 'tool',
    params: [
      { key: 'periods', label: 'Periods', type: 'months', default: 12, min: 1, max: 60, chipDisplay: (v: number) => `${v}mo` },
      { key: 'opex_breakdown', label: 'Dept Breakdown', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No', value: 'false' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'revenue_projection',
    label: 'Revenue Projection',
    domain: 'modeling',
    icon: 'TrendingUp',
    description: 'Revenue projection with growth method',
    tool: 'revenue_projection',
    kind: 'tool',
    params: [
      { key: 'method', label: 'Method', type: 'select', default: 'growth', options: [{ label: 'Decay', value: 'decay' }, { label: 'Growth', value: 'growth' }, { label: 'S-Curve', value: 's_curve' }] },
      { key: 'periods', label: 'Periods', type: 'months', default: 12, min: 1, max: 60, chipDisplay: (v: number) => `${v}mo` },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'financial_calc',
    label: 'Financial Calculator',
    domain: 'modeling',
    icon: 'Calculator',
    description: 'NPV, IRR, PV, FV, PMT calculations',
    tool: 'financial_calculator',
    kind: 'tool',
    params: [
      { key: 'function', label: 'Function', type: 'select', default: 'npv', options: [{ label: 'NPV', value: 'npv' }, { label: 'IRR', value: 'irr' }, { label: 'PV', value: 'pv' }, { label: 'FV', value: 'fv' }] },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'run_fpa',
    label: 'Run FPA',
    domain: 'modeling',
    icon: 'Play',
    description: 'Run FPA analysis (forecast, stress, sensitivity)',
    tool: 'run_fpa',
    kind: 'tool',
    params: [
      { key: 'method', label: 'Method', type: 'select', default: 'forecast', options: [{ label: 'Forecast', value: 'forecast' }, { label: 'Stress', value: 'stress' }, { label: 'Sensitivity', value: 'sensitivity' }] },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
];

// ---------------------------------------------------------------------------
// V2: Ops Domain
// ---------------------------------------------------------------------------

const opsChips: ChipDef[] = [
  {
    id: 'runway',
    label: 'Runway',
    domain: 'ops',
    icon: 'Timer',
    description: 'Calculate runway in months',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'runway_months' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'burn_rate',
    label: 'Burn Rate',
    domain: 'ops',
    icon: 'Flame',
    description: 'Calculate monthly burn rate',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'burn_rate' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'hiring_plan',
    label: 'Hiring Plan',
    domain: 'ops',
    icon: 'UserPlus',
    description: 'Generate hiring plan by department',
    tool: 'run_cash_flow_model',
    kind: 'operational',
    params: [
      { key: 'headcount_by_dept', label: 'By Dept', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No', value: 'false' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'budget_create',
    label: 'Budget Create',
    domain: 'ops',
    icon: 'FilePlus',
    description: 'Create a budget',
    tool: 'fpa_budget_create',
    kind: 'operational',
    params: [
      { key: 'name', label: 'Name', type: 'text', default: '' },
      { key: 'periods', label: 'Periods', type: 'months', default: 12, min: 1, max: 60 },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'budget_lines',
    label: 'Budget Lines',
    domain: 'ops',
    icon: 'List',
    description: 'View budget line items',
    tool: 'fpa_budget_lines',
    kind: 'operational',
    params: [
      { key: 'category', label: 'Category', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  // -- Liquidity Management & Auto-Budget (deep subcategory/subcomponent) ------
  {
    id: 'liquidity_model',
    label: 'Liquidity Model',
    domain: 'fpa',
    icon: 'Droplets',
    description: 'Advanced cash flow planning at subcategory + subcomponent depth',
    tool: 'liquidity_model',
    kind: 'operational',
    params: [
      { key: 'months', label: 'Months', type: 'months', default: 24, min: 1, max: 60, chipDisplay: (v: number) => `${v}mo` },
      { key: 'start_period', label: 'Start (YYYY-MM)', type: 'text', default: '' },
    ],
    inputPorts: [PORTS.driversIn()],
    outputPorts: [PORTS.cashFlowOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 30000,
  },
  {
    id: 'liquidity_scenarios',
    label: 'Liquidity Scenarios',
    domain: 'fpa',
    icon: 'GitBranch',
    description: 'Bull/base/bear liquidity scenario comparison',
    tool: 'liquidity_scenarios',
    kind: 'operational',
    params: [
      { key: 'months', label: 'Months', type: 'months', default: 24, min: 1, max: 60, chipDisplay: (v: number) => `${v}mo` },
    ],
    inputPorts: [PORTS.driversIn()],
    outputPorts: [PORTS.cashFlowOut()],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 60000,
  },
  {
    id: 'liquidity_sensitivity',
    label: 'Liquidity Sensitivity',
    domain: 'fpa',
    icon: 'Gauge',
    description: 'Runway impact analysis: which cost lines matter most',
    tool: 'liquidity_sensitivity',
    kind: 'operational',
    params: [
      { key: 'months', label: 'Months', type: 'months', default: 24, min: 1, max: 60 },
    ],
    inputPorts: [],
    outputPorts: [PORTS.tableOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 120000,
  },
  {
    id: 'auto_budget',
    label: 'Auto Budget',
    domain: 'fpa',
    icon: 'Calculator',
    description: 'Auto-generate budget at subcategory depth from actuals',
    tool: 'auto_budget',
    kind: 'operational',
    params: [
      { key: 'fiscal_year', label: 'Fiscal Year', type: 'number', default: new Date().getFullYear() + 1, min: 2020, max: 2030 },
      { key: 'mode', label: 'Mode', type: 'select', default: 'actuals_forward', options: [{ label: 'Actuals Forward', value: 'actuals_forward' }, { label: 'Zero Based', value: 'zero_based' }, { label: 'Target Margin', value: 'target_margin' }] },
      { key: 'target_ebitda_margin', label: 'Target EBITDA %', type: 'number', default: 15, min: -100, max: 100 },
      { key: 'persist', label: 'Save to DB', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No (preview)', value: 'false' }] },
    ],
    inputPorts: [PORTS.driversIn()],
    outputPorts: [PORTS.tableOut()],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 30000,
  },
  {
    id: 'crm_search',
    label: 'CRM Search',
    domain: 'ops',
    icon: 'Search',
    description: 'Search CRM records',
    tool: 'crm_search',
    kind: 'operational',
    params: [
      { key: 'query', label: 'Query', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'crm_log',
    label: 'CRM Log',
    domain: 'ops',
    icon: 'PenLine',
    description: 'Log a CRM interaction',
    tool: 'crm_log_interaction',
    kind: 'operational',
    params: [
      { key: 'type', label: 'Type', type: 'select', default: 'note', options: [{ label: 'Meeting', value: 'meeting' }, { label: 'Call', value: 'call' }, { label: 'Note', value: 'note' }] },
    ],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'crm_pipeline',
    label: 'CRM Pipeline',
    domain: 'ops',
    icon: 'KanbanSquare',
    description: 'Update CRM pipeline stage',
    tool: 'crm_pipeline_update',
    kind: 'operational',
    params: [
      { key: 'stage', label: 'Stage', type: 'text', default: '' },
      { key: 'deal', label: 'Deal', type: 'text', default: '' },
    ],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'ma_model',
    label: 'M&A Model',
    domain: 'ops',
    icon: 'Merge',
    description: 'Run M&A workflow with synergy assumptions',
    tool: 'ma_workflow',
    kind: 'tool',
    params: [
      { key: 'acquirer', label: 'Acquirer', type: 'text', default: '' },
      { key: 'target', label: 'Target', type: 'text', default: '' },
      { key: 'deal_type', label: 'Deal Type', type: 'select', default: 'strategic', options: [{ label: 'Strategic', value: 'strategic' }, { label: 'Financial', value: 'financial' }, { label: 'Hostile', value: 'hostile' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'compliance_check',
    label: 'Compliance Check',
    domain: 'ops',
    icon: 'ShieldCheck',
    description: 'Run compliance check by jurisdiction',
    tool: 'compliance_check',
    kind: 'operational',
    params: [
      { key: 'jurisdiction', label: 'Jurisdiction', type: 'select', default: 'us', options: [{ label: 'United States', value: 'us' }, { label: 'United Kingdom', value: 'uk' }, { label: 'EU (GDPR)', value: 'eu' }, { label: 'Switzerland', value: 'ch' }, { label: 'Singapore', value: 'sg' }, { label: 'Cayman Islands', value: 'ky' }] },
      { key: 'check_type', label: 'Check Type', type: 'select', default: 'full', options: [{ label: 'Full Compliance', value: 'full' }, { label: 'AML/KYC', value: 'aml_kyc' }, { label: 'Data Privacy', value: 'data_privacy' }, { label: 'Fund Regulatory', value: 'fund_regulatory' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
];

// ---------------------------------------------------------------------------
// V2: Formula Chips (Operational Formulas)
// ---------------------------------------------------------------------------

const formulaChips: ChipDef[] = [
  {
    id: 'ltv_cac',
    label: 'LTV/CAC',
    domain: 'ops',
    icon: 'Ratio',
    description: 'LTV/CAC ratio',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'ltv_cac_ratio' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'rule_of_40',
    label: 'Rule of 40',
    domain: 'ops',
    icon: 'Target',
    description: 'Rule of 40 score',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'rule_of_40' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'magic_number',
    label: 'Magic Number',
    domain: 'ops',
    icon: 'Sparkles',
    description: 'SaaS magic number',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'magic_number' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'cac_payback',
    label: 'CAC Payback',
    domain: 'ops',
    icon: 'Clock',
    description: 'CAC payback period in months',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'cac_payback' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'rev_per_employee',
    label: 'Rev/Employee',
    domain: 'ops',
    icon: 'Users',
    description: 'Revenue per employee',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'revenue_per_employee' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'gross_margin',
    label: 'Gross Margin',
    domain: 'ops',
    icon: 'Percent',
    description: 'Gross margin percentage',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'gross_margin' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'net_retention',
    label: 'Net Retention',
    domain: 'ops',
    icon: 'RefreshCw',
    description: 'Net revenue retention rate',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'net_revenue_retention' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'custom_kpi',
    label: 'Custom KPI',
    domain: 'ops',
    icon: 'Sliders',
    description: 'Custom KPI from expression',
    tool: 'financial_calculator',
    kind: 'formula',
    params: [
      { key: 'expression', label: 'Expression', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// V2: Bridge Domain
// ---------------------------------------------------------------------------

const bridgeChips: ChipDef[] = [
  {
    id: 'contract_to_pnl',
    label: 'Contract → P&L',
    domain: 'bridge',
    icon: 'ArrowRight',
    description: 'Bridge commercial contracts to P&L line items',
    tool: 'contract_pnl_attribution',
    kind: 'bridge',
    bridgeTools: ['contract_pnl_attribution'],
    params: [
      { key: 'period', label: 'Period', type: 'select', default: 'current', options: [{ label: 'Current', value: 'current' }, { label: 'YTD', value: 'ytd' }, { label: 'Full Term', value: 'full' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'contract_changes_to_pnl',
    label: 'Contract Changes → P&L',
    domain: 'bridge',
    icon: 'FileDiff',
    description: 'Bridge redline contract changes to financial impact',
    tool: 'model_contract_changes',
    kind: 'bridge',
    bridgeTools: ['model_contract_changes'],
    params: [
      { key: 'change_description', label: 'Change', type: 'text', default: '' },
    ],
    outputRenderer: 'delta',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'cap_table_to_val',
    label: 'Cap Table → Valuation',
    domain: 'bridge',
    icon: 'Link2',
    description: 'Bridge ownership to equity value',
    tool: 'cap_table_evolution',
    kind: 'bridge',
    bridgeTools: ['cap_table_evolution', 'run_valuation'],
    params: [
      { key: 'method', label: 'Valuation Method', type: 'select', default: 'auto', options: [{ label: 'Auto', value: 'auto' }, { label: 'DCF', value: 'dcf' }, { label: 'Revenue Multiple', value: 'revenue_multiple' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'legal_to_financial',
    label: 'Legal → Financial',
    domain: 'bridge',
    icon: 'Scale',
    description: 'Bridge legal terms to financial parameters',
    tool: 'contract_lifecycle_query',
    kind: 'bridge',
    bridgeTools: ['contract_lifecycle_query'],
    params: [
      { key: 'focus', label: 'Focus', type: 'select', default: 'all', options: [{ label: 'All Terms', value: 'all' }, { label: 'Revenue Impact', value: 'revenue' }, { label: 'Liability', value: 'liability' }, { label: 'Covenants', value: 'covenants' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'intercompany_to_tp',
    label: 'Intercompany → TP',
    domain: 'bridge',
    icon: 'Building2',
    description: 'Bridge intercompany agreements to transfer pricing',
    tool: 'tp_analyze_transaction',
    kind: 'bridge',
    bridgeTools: ['tp_analyze_transaction'],
    params: [
      { key: 'method', label: 'TP Method', type: 'select', default: 'auto', options: [{ label: 'Auto', value: 'auto' }, { label: 'CUP', value: 'cup' }, { label: 'Cost Plus', value: 'cost_plus' }, { label: 'Profit Split', value: 'profit_split' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
];

// ---------------------------------------------------------------------------
// V2: Chart Domain
// ---------------------------------------------------------------------------

const chartChipBase = (id: string, label: string, icon: string, desc: string, chartType: string): ChipDef => ({
  id, label, domain: 'chart', icon, description: desc, tool: 'generate_chart', kind: 'chart',
  params: [
    { key: 'type', label: 'Chart Type', type: 'text', default: chartType },
    { key: 'title', label: 'Title', type: 'text', default: '' },
    { key: 'metric', label: 'Metric', type: 'select', default: 'auto', options: [{ label: 'Auto (from input)', value: 'auto' }, { label: 'Revenue', value: 'revenue' }, { label: 'EBITDA', value: 'ebitda' }, { label: 'Cash Balance', value: 'cash_balance' }, { label: 'Burn Rate', value: 'burn_rate' }, { label: 'Headcount', value: 'headcount' }, { label: 'Valuation', value: 'valuation' }] },
    { key: 'periods', label: 'Periods', type: 'months', default: 12, min: 1, max: 60 },
  ],
  inputPorts: [PORTS.dataIn(true)],
  outputPorts: [PORTS.chartOut()],
  outputRenderer: 'chart', costTier: 'free', timeoutMs: 10000,
});

const chartChips: ChipDef[] = [
  chartChipBase('line_chart', 'Line Chart', 'LineChart', 'Time series & trends', 'line'),
  chartChipBase('bar_chart', 'Bar Chart', 'BarChart3', 'Comparisons', 'bar'),
  chartChipBase('stacked_bar', 'Stacked Bar', 'BarChart4', 'Composition over time', 'stacked_bar'),
  chartChipBase('area_chart', 'Area Chart', 'AreaChart', 'Cumulative & ranges', 'area'),
  chartChipBase('waterfall_chart', 'Waterfall', 'BarChart', 'P&L bridge, cash flow waterfall', 'waterfall'),
  chartChipBase('sankey_chart', 'Sankey', 'GitFork', 'Ownership flow, cap table visualization', 'sankey'),
  chartChipBase('tornado_chart', 'Tornado', 'ArrowUpDown', 'Sensitivity analysis tornado', 'tornado'),
  chartChipBase('heatmap_chart', 'Heatmap', 'Grid3x3', 'Correlation & sensitivity matrix', 'heatmap'),
  chartChipBase('bubble_chart', 'Bubble', 'Circle', '3D comparison', 'bubble'),
  chartChipBase('scatter_chart', 'Scatter', 'ScatterChart', 'Correlation & clustering', 'scatter'),
  chartChipBase('treemap_chart', 'Treemap', 'LayoutGrid', 'Hierarchical composition', 'treemap'),
  chartChipBase('funnel_chart', 'Funnel', 'Filter', 'Pipeline & conversion', 'funnel'),
  chartChipBase('radar_chart', 'Radar', 'Radar', 'Multi-metric comparison', 'radar_comparison'),
  chartChipBase('mc_histogram', 'MC Histogram', 'BarChart2', 'Monte Carlo distribution histogram', 'monte_carlo_histogram'),
  chartChipBase('mc_fan', 'MC Fan', 'Wind', 'Monte Carlo probability fan', 'monte_carlo_fan'),
  chartChipBase('probability_cloud', 'Prob Cloud', 'Cloud', 'Exit scenario probability cloud', 'probability_cloud'),
];

// ---------------------------------------------------------------------------
// V2: Transform Domain
// ---------------------------------------------------------------------------

const transformChips: ChipDef[] = [
  {
    id: 'fx_convert',
    label: 'FX Convert',
    domain: 'transform',
    icon: 'ArrowLeftRight',
    description: 'Convert currency',
    tool: 'convert_currency',
    kind: 'tool',
    params: [
      { key: 'target_currency', label: 'Target Currency', type: 'select', default: 'USD', options: [{ label: 'USD', value: 'USD' }, { label: 'EUR', value: 'EUR' }, { label: 'GBP', value: 'GBP' }, { label: 'CHF', value: 'CHF' }, { label: 'JPY', value: 'JPY' }, { label: 'CAD', value: 'CAD' }, { label: 'AUD', value: 'AUD' }, { label: 'SGD', value: 'SGD' }] },
      { key: 'rate_source', label: 'Rate Source', type: 'select', default: 'live', options: [{ label: 'Live Rate', value: 'live' }, { label: 'Fixed Rate', value: 'fixed' }, { label: 'Period Average', value: 'average' }] },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'fx_impact_transform',
    label: 'FX Impact',
    domain: 'transform',
    icon: 'Coins',
    description: 'FX portfolio impact analysis',
    tool: 'fx_portfolio_impact',
    kind: 'tool',
    params: [
      { key: 'base_currency', label: 'Base', type: 'select', default: 'USD', options: [{ label: 'USD', value: 'USD' }, { label: 'EUR', value: 'EUR' }, { label: 'GBP', value: 'GBP' }] },
      { key: 'shock_pct', label: 'Shock %', type: 'percent', default: 10, min: 1, max: 50 },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'seasonality_detect',
    label: 'Seasonality Detect',
    domain: 'transform',
    icon: 'CalendarDays',
    description: 'Detect seasonal patterns in data',
    tool: 'fpa_detect_seasonality',
    kind: 'tool',
    params: [
      { key: 'metric', label: 'Metric', type: 'select', default: 'revenue', options: [{ label: 'Revenue', value: 'revenue' }, { label: 'COGS', value: 'cogs' }, { label: 'Headcount', value: 'headcount' }, { label: 'Burn Rate', value: 'burn_rate' }] },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'seasonality_apply',
    label: 'Seasonality Apply',
    domain: 'transform',
    icon: 'CalendarCheck',
    description: 'Apply seasonal pattern to forecast',
    tool: 'fpa_apply_seasonality',
    kind: 'tool',
    params: [
      { key: 'pattern', label: 'Pattern Source', type: 'select', default: 'auto', options: [{ label: 'Auto-detect from actuals', value: 'auto' }, { label: 'Q4 Heavy (SaaS)', value: 'q4_heavy' }, { label: 'Summer Dip', value: 'summer_dip' }, { label: 'Linear (no seasonality)', value: 'none' }, { label: 'Custom', value: 'custom' }] },
      { key: 'strength', label: 'Strength', type: 'percent', default: 100, min: 0, max: 200 },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'correlate',
    label: 'Correlate',
    domain: 'transform',
    icon: 'Link2',
    description: 'Correlate actuals between metric pairs',
    tool: 'fpa_correlate_actuals',
    kind: 'tool',
    params: [
      { key: 'metric_a', label: 'Metric A', type: 'metric', default: 'revenue' },
      { key: 'metric_b', label: 'Metric B', type: 'metric', default: 'headcount' },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// V2: Loop Connectors
// ---------------------------------------------------------------------------

const loopChips: ChipDef[] = [
  {
    id: 'for_each_company',
    label: 'For Each Company',
    domain: 'ops',
    icon: 'Repeat',
    description: 'Iterate over portfolio companies',
    tool: '_loop',
    kind: 'loop',
    loopOver: 'companies',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'for_each_scenario',
    label: 'For Each Scenario',
    domain: 'ops',
    icon: 'Repeat',
    description: 'Iterate over scenario branches',
    tool: '_loop',
    kind: 'loop',
    loopOver: 'scenarios',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'for_each_period',
    label: 'For Each Period',
    domain: 'ops',
    icon: 'Repeat',
    description: 'Iterate over time periods',
    tool: '_loop',
    kind: 'loop',
    loopOver: 'periods',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 5000,
  },
];

// ---------------------------------------------------------------------------
// V2: Conditional Connectors
// ---------------------------------------------------------------------------

const conditionalChips: ChipDef[] = [
  {
    id: 'if_runway_lt',
    label: 'If Runway < X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on runway threshold',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'runway_months',
    conditionOp: '<',
    params: [
      { key: 'threshold', label: 'Months', type: 'number', default: 6, min: 0, max: 36 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'if_growth_gt',
    label: 'If Growth > X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on growth rate',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'growth_rate',
    conditionOp: '>',
    params: [
      { key: 'threshold', label: 'Percent', type: 'percent', default: 25, min: 0, max: 200 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'if_valuation_gt',
    label: 'If Valuation > X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on valuation',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'valuation',
    conditionOp: '>',
    params: [
      { key: 'threshold', label: 'Value', type: 'currency', default: 10000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'if_burn_gt',
    label: 'If Burn > X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on burn rate',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'burn_rate',
    conditionOp: '>',
    params: [
      { key: 'threshold', label: 'Amount', type: 'currency', default: 500000, chipDisplay: (v: number) => `$${fmt(v / 1000)}k` },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'if_churn_gt',
    label: 'If Churn > X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on churn rate',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'churn_rate',
    conditionOp: '>',
    params: [
      { key: 'threshold', label: 'Percent', type: 'percent', default: 5, min: 0, max: 50 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
];

// ---------------------------------------------------------------------------
// V2: Assumption Connectors
// ---------------------------------------------------------------------------

const assumptionChips: ChipDef[] = [
  {
    id: 'growth_assumptions',
    label: 'Growth Assumptions',
    domain: 'driver',
    icon: 'TrendingUp',
    description: 'Bundle growth driver overrides',
    tool: '_assumption',
    kind: 'assumption',
    assumptionKeys: ['revenue_growth', 'churn_rate', 'pricing_change', 'expansion_rate'],
    params: [
      { key: 'revenue_growth', label: 'Rev Growth', type: 'percent', default: 20 },
      { key: 'churn_rate', label: 'Churn', type: 'percent', default: 5 },
      { key: 'pricing_change', label: 'Pricing Δ', type: 'percent', default: 0 },
      { key: 'expansion_rate', label: 'Expansion', type: 'percent', default: 10 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'cost_assumptions',
    label: 'Cost Assumptions',
    domain: 'driver',
    icon: 'Wallet',
    description: 'Bundle cost driver overrides',
    tool: '_assumption',
    kind: 'assumption',
    assumptionKeys: ['headcount_change', 'avg_salary', 'cogs_pct', 'opex_growth'],
    params: [
      { key: 'headcount_change', label: 'Headcount Δ', type: 'number', default: 5 },
      { key: 'avg_salary', label: 'Avg Salary', type: 'currency', default: 80000 },
      { key: 'cogs_pct', label: 'COGS %', type: 'percent', default: 35 },
      { key: 'opex_growth', label: 'Opex Growth', type: 'percent', default: 10 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'funding_assumptions',
    label: 'Funding Assumptions',
    domain: 'driver',
    icon: 'Banknote',
    description: 'Bundle funding driver overrides',
    tool: '_assumption',
    kind: 'assumption',
    assumptionKeys: ['raise_amount', 'dilution_pct', 'timeline_months', 'valuation_cap'],
    params: [
      { key: 'raise_amount', label: 'Raise', type: 'currency', default: 5000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'dilution_pct', label: 'Dilution', type: 'percent', default: 20 },
      { key: 'timeline_months', label: 'Timeline', type: 'months', default: 6 },
      { key: 'valuation_cap', label: 'Val Cap', type: 'currency', default: 20000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'macro_assumptions',
    label: 'Macro Assumptions',
    domain: 'driver',
    icon: 'Globe',
    description: 'Bundle macro driver overrides',
    tool: '_assumption',
    kind: 'assumption',
    assumptionKeys: ['interest_rate', 'inflation_rate', 'fx_rate_change', 'gdp_growth'],
    params: [
      { key: 'interest_rate', label: 'Interest', type: 'percent', default: 5 },
      { key: 'inflation_rate', label: 'Inflation', type: 'percent', default: 3 },
      { key: 'fx_rate_change', label: 'FX Δ', type: 'percent', default: 0 },
      { key: 'gdp_growth', label: 'GDP Growth', type: 'percent', default: 2 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
];

// ---------------------------------------------------------------------------
// V2: Event Connectors (Events/Priors Integration)
// ---------------------------------------------------------------------------

const eventChips: ChipDef[] = [
  {
    id: 'business_event',
    label: 'Business Event',
    domain: 'modeling',
    icon: 'Briefcase',
    description: 'Add a business event to model construction',
    tool: 'analyse_macro_event',
    kind: 'event',
    eventCategory: 'business',
    params: [
      { key: 'event', label: 'Event', type: 'text', default: '' },
      { key: 'probability', label: 'Probability', type: 'percent', default: 80, min: 0, max: 100 },
      { key: 'timing', label: 'Timing', type: 'text', default: '' },
    ],
    outputRenderer: 'raw',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'macro_event',
    label: 'Macro Event',
    domain: 'modeling',
    icon: 'Globe',
    description: 'Add a macro event to model construction',
    tool: 'analyse_macro_event',
    kind: 'event',
    eventCategory: 'macro',
    params: [
      { key: 'event', label: 'Event', type: 'text', default: '' },
      { key: 'probability', label: 'Probability', type: 'percent', default: 60, min: 0, max: 100 },
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    outputRenderer: 'raw',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'funding_event',
    label: 'Funding Event',
    domain: 'modeling',
    icon: 'Banknote',
    description: 'Add a funding event to model construction',
    tool: '_funding_event',
    kind: 'event',
    eventCategory: 'funding',
    params: [
      { key: 'type', label: 'Type', type: 'select', default: 'equity', options: [{ label: 'Equity', value: 'equity' }, { label: 'Debt', value: 'debt' }, { label: 'SAFE', value: 'safe' }] },
      { key: 'amount', label: 'Amount', type: 'currency', default: 5000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'period', label: 'Period', type: 'months', default: 3 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'operational_event',
    label: 'Ops Event',
    domain: 'modeling',
    icon: 'Settings',
    description: 'Add an operational event to model construction',
    tool: 'analyse_macro_event',
    kind: 'event',
    eventCategory: 'operational',
    params: [
      { key: 'event', label: 'Event', type: 'text', default: '' },
      { key: 'probability', label: 'Probability', type: 'percent', default: 80, min: 0, max: 100 },
    ],
    outputRenderer: 'raw',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'market_event',
    label: 'Market Event',
    domain: 'modeling',
    icon: 'TrendingDown',
    description: 'Add a market event to model construction',
    tool: 'analyse_macro_event',
    kind: 'event',
    eventCategory: 'market',
    params: [
      { key: 'event', label: 'Event', type: 'text', default: '' },
      { key: 'probability', label: 'Probability', type: 'percent', default: 50, min: 0, max: 100 },
    ],
    outputRenderer: 'raw',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'add_event_chain',
    label: 'Event Chain',
    domain: 'modeling',
    icon: 'Link',
    description: 'Build full event chain from NL description',
    tool: 'construct_forecast_model',
    kind: 'event',
    params: [
      { key: 'prompt', label: 'Description', type: 'text', default: '' },
    ],
    outputRenderer: 'raw',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
];

// ---------------------------------------------------------------------------
// V2: Prior Connectors (Events/Priors Integration)
// ---------------------------------------------------------------------------

const priorChips: ChipDef[] = [
  {
    id: 'set_confidence',
    label: 'Set Confidence',
    domain: 'modeling',
    icon: 'Gauge',
    description: 'Set confidence level on downstream curves',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['confidence'],
    params: [
      { key: 'confidence', label: 'Confidence', type: 'percent', default: 80, min: 0, max: 100 },
      { key: 'distribution', label: 'Distribution', type: 'select', default: 'normal', options: [{ label: 'Normal', value: 'normal' }, { label: 'Beta', value: 'beta' }, { label: 'Triangular', value: 'triangular' }] },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'set_ceiling',
    label: 'Set Ceiling',
    domain: 'modeling',
    icon: 'ArrowUpToLine',
    description: 'Set ceiling on a curve metric',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['ceiling'],
    params: [
      { key: 'ceiling', label: 'Ceiling', type: 'currency', default: 10000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'metric', label: 'Metric', type: 'metric', default: 'revenue' },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'set_floor',
    label: 'Set Floor',
    domain: 'modeling',
    icon: 'ArrowDownToLine',
    description: 'Set floor on a curve metric',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['floor'],
    params: [
      { key: 'floor', label: 'Floor', type: 'currency', default: 0 },
      { key: 'metric', label: 'Metric', type: 'metric', default: 'revenue' },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'growth_prior',
    label: 'Growth Prior',
    domain: 'modeling',
    icon: 'TrendingUp',
    description: 'Set confidence and ceiling on revenue curve',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['revenue.confidence', 'revenue.ceiling'],
    params: [
      { key: 'confidence', label: 'Confidence', type: 'percent', default: 90, min: 0, max: 100 },
      { key: 'ceiling', label: 'Ceiling', type: 'currency', default: 2000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'cost_prior',
    label: 'Cost Prior',
    domain: 'modeling',
    icon: 'Wallet',
    description: 'Set confidence on cost curves',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['opex.confidence', 'cogs.confidence'],
    params: [
      { key: 'confidence', label: 'Confidence', type: 'percent', default: 70, min: 0, max: 100 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
];

// ---------------------------------------------------------------------------
// Combined Registry
// ---------------------------------------------------------------------------

export const CHIP_REGISTRY: ChipDef[] = [
  ...fpaChips,
  ...scenarioChips,
  ...analyticsChips,
  ...capitalChips,
  ...fundingChips,
  ...macroChips,
  ...intelChips,
  ...reportChips,
  ...complianceChips,
  ...portfolioChips,
  ...commsChips,
  ...dataChips,
  // V2 domains:
  ...modelingChips,
  ...opsChips,
  ...formulaChips,
  ...bridgeChips,
  ...chartChips,
  ...transformChips,
  // V2 connectors:
  ...loopChips,
  ...conditionalChips,
  ...assumptionChips,
  ...eventChips,
  ...priorChips,
];

/** Lookup by chip ID */
export const CHIP_BY_ID: Record<string, ChipDef> = Object.fromEntries(
  CHIP_REGISTRY.map((c) => [c.id, c]),
);

/** Group chips by domain */
export function chipsByDomain(): Record<string, ChipDef[]> {
  const grouped: Record<string, ChipDef[]> = {};
  for (const chip of CHIP_REGISTRY) {
    (grouped[chip.domain] ??= []).push(chip);
  }
  return grouped;
}

/** Search chips by label/description */
export function searchChips(query: string): ChipDef[] {
  const q = query.toLowerCase().trim();
  if (!q) return CHIP_REGISTRY;
  return CHIP_REGISTRY.filter(
    (c) =>
      c.label.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.domain.includes(q) ||
      c.tool.toLowerCase().includes(q),
  );
}
