// ---------------------------------------------------------------------------
// Chip Registry — Every backend tool as a chip definition
// ---------------------------------------------------------------------------

import type { ChipDef } from './types';

function fmt(n: number): string {
  if (n >= 1000) return `${n / 1000}k`;
  return String(n);
}

// ---------------------------------------------------------------------------
// FP&A
// ---------------------------------------------------------------------------

const fpaChips: ChipDef[] = [
  {
    id: 'forecast',
    label: 'Forecast',
    domain: 'fpa',
    icon: 'TrendingUp',
    description: 'Run a financial forecast',
    tool: 'fpa_forecast',
    params: [
      { key: 'method', label: 'Method', type: 'select', default: 'linear', options: [{ label: 'Linear', value: 'linear' }, { label: 'Exponential', value: 'exponential' }, { label: 'CAGR', value: 'cagr' }, { label: 'Custom', value: 'custom' }] },
      { key: 'metric', label: 'Metric', type: 'metric', default: 'revenue' },
      { key: 'periods', label: 'Periods', type: 'months', default: 12, min: 1, max: 60, chipDisplay: (v: number) => `${v}mo` },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'custom_model',
    label: 'Custom Model',
    domain: 'fpa',
    icon: 'Wand2',
    description: 'Construct a custom forecast model from description',
    tool: 'construct_forecast_model',
    params: [
      { key: 'prompt', label: 'Description', type: 'text', default: '' },
    ],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'execute_model',
    label: 'Execute Model',
    domain: 'fpa',
    icon: 'Play',
    description: 'Execute a constructed forecast model',
    tool: 'execute_forecast_model',
    params: [
      { key: 'model_id', label: 'Model', type: 'text', default: '' },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
  {
    id: 'pnl',
    label: 'P&L',
    domain: 'fpa',
    icon: 'Receipt',
    description: 'Profit & loss statement',
    tool: 'fpa_pnl',
    params: [
      { key: 'periods', label: 'Periods', type: 'months', default: 12 },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'balance_sheet',
    label: 'Balance Sheet',
    domain: 'fpa',
    icon: 'Scale',
    description: 'Balance sheet snapshot',
    tool: 'fpa_balance_sheet',
    params: [
      { key: 'date', label: 'Date', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'cash_flow',
    label: 'Cash Flow',
    domain: 'fpa',
    icon: 'ArrowDownUp',
    description: 'Cash flow statement',
    tool: 'fpa_cash_flow',
    params: [
      { key: 'periods', label: 'Periods', type: 'months', default: 12 },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'variance',
    label: 'Variance',
    domain: 'fpa',
    icon: 'ArrowLeftRight',
    description: 'Variance analysis (actual vs forecast)',
    tool: 'fpa_variance',
    params: [
      { key: 'period', label: 'Period', type: 'text', default: '' },
    ],
    outputRenderer: 'delta',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'rolling_forecast',
    label: 'Rolling Forecast',
    domain: 'fpa',
    icon: 'RefreshCw',
    description: 'Rolling 13-week forecast',
    tool: 'fpa_rolling_forecast',
    params: [
      { key: 'weeks', label: 'Weeks', type: 'number', default: 13, min: 4, max: 26 },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'kpi_dashboard',
    label: 'KPI Dashboard',
    domain: 'fpa',
    icon: 'LayoutDashboard',
    description: 'Key performance indicators',
    tool: 'fpa_kpi_dashboard',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'unit_economics',
    label: 'Unit Economics',
    domain: 'fpa',
    icon: 'Calculator',
    description: 'LTV, CAC, magic number, payback period',
    tool: 'fpa_computed_metrics',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// Scenario & Stress Testing
// ---------------------------------------------------------------------------

const scenarioChips: ChipDef[] = [
  {
    id: 'scenario',
    label: 'Scenario',
    domain: 'scenario',
    icon: 'GitBranch',
    description: 'Create a scenario branch with driver overrides',
    tool: 'fpa_scenario_create',
    params: [
      { key: 'name', label: 'Name', type: 'text', default: '' },
    ],
    produces: ['scenario_id'],
    outputRenderer: 'tree',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'compare_scenarios',
    label: 'Compare Scenarios',
    domain: 'scenario',
    icon: 'Columns',
    description: 'Side-by-side scenario comparison',
    tool: 'fpa_scenario_compare',
    params: [],
    accepts: ['scenario'],
    outputRenderer: 'delta',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'scenario_tree',
    label: 'Scenario Tree',
    domain: 'scenario',
    icon: 'Network',
    description: 'Visualize the full scenario tree',
    tool: 'run_scenario_tree',
    params: [
      { key: 'depth', label: 'Depth', type: 'number', default: 3, min: 1, max: 5 },
    ],
    outputRenderer: 'tree',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'stress_test',
    label: 'Stress Test',
    domain: 'scenario',
    icon: 'Zap',
    description: 'Stress test portfolio or scenario',
    tool: 'stress_test_portfolio',
    params: [
      { key: 'shock_type', label: 'Shock', type: 'select', default: 'revenue_drop', options: [{ label: 'Revenue Drop', value: 'revenue_drop' }, { label: 'Cost Spike', value: 'cost_spike' }, { label: 'Churn Increase', value: 'churn_increase' }] },
      { key: 'magnitude', label: 'Magnitude', type: 'percent', default: 30, min: 5, max: 90 },
    ],
    accepts: ['scenario', 'macro'],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'bull_bear_base',
    label: 'Bull/Bear/Base',
    domain: 'scenario',
    icon: 'ArrowUpDown',
    description: 'Generate bull, bear, and base case scenarios',
    tool: 'run_bull_bear_base',
    params: [],
    outputRenderer: 'delta',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'three_way_cash_flow',
    label: 'Three-Way Cash Flow',
    domain: 'scenario',
    icon: 'Split',
    description: 'Cash flow across three scenario paths',
    tool: 'three_scenario_cash_flow',
    params: [],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 25000,
  },
  {
    id: 'world_model',
    label: 'World Model',
    domain: 'scenario',
    icon: 'Globe2',
    description: 'Multi-factor world model scenario',
    tool: 'world_model_scenario',
    params: [],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
];

// ---------------------------------------------------------------------------
// Simulation & Analytics
// ---------------------------------------------------------------------------

const analyticsChips: ChipDef[] = [
  {
    id: 'monte_carlo',
    label: 'Monte Carlo',
    domain: 'analytics',
    icon: 'Dice5',
    description: 'Monte Carlo simulation',
    tool: 'fpa_monte_carlo',
    params: [
      { key: 'iterations', label: 'Iterations', type: 'number', default: 10000, min: 100, max: 100000, step: 1000, chipDisplay: (v: number) => fmt(v) },
      { key: 'target_metric', label: 'Metric', type: 'metric', default: 'revenue' },
    ],
    accepts: ['fpa', 'scenario'],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'sensitivity',
    label: 'Sensitivity',
    domain: 'analytics',
    icon: 'Grid3x3',
    description: 'Sensitivity matrix analysis',
    tool: 'sensitivity_matrix',
    params: [
      { key: 'target_metric', label: 'Target', type: 'metric', default: 'revenue' },
    ],
    outputRenderer: 'matrix',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'regression',
    label: 'Regression',
    domain: 'analytics',
    icon: 'LineChart',
    description: 'Regression analysis',
    tool: 'fpa_regression',
    params: [
      { key: 'method', label: 'Method', type: 'select', default: 'linear', options: [{ label: 'Linear', value: 'linear' }, { label: 'Polynomial', value: 'poly' }, { label: 'LOESS', value: 'loess' }] },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'seasonality',
    label: 'Seasonality',
    domain: 'analytics',
    icon: 'CalendarDays',
    description: 'Detect seasonal patterns',
    tool: 'fpa_detect_seasonality',
    params: [],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'correlation',
    label: 'Correlation',
    domain: 'analytics',
    icon: 'Link2',
    description: 'Correlate actuals between metrics',
    tool: 'fpa_correlate_actuals',
    params: [],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'driver_impact',
    label: 'Driver Impact',
    domain: 'analytics',
    icon: 'BarChart3',
    description: 'Driver impact ranking (tornado chart)',
    tool: 'fpa_driver_impact_ranking',
    params: [],
    outputRenderer: 'tornado',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'trace_impact',
    label: 'Trace Impact',
    domain: 'analytics',
    icon: 'Workflow',
    description: 'Trace strategic impact from a source driver',
    tool: 'fpa_trace_strategic_impact',
    params: [
      { key: 'source_driver', label: 'Driver', type: 'text', default: '' },
    ],
    outputRenderer: 'sankey',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
];

// ---------------------------------------------------------------------------
// Valuation & Cap Table
// ---------------------------------------------------------------------------

const capitalChips: ChipDef[] = [
  {
    id: 'valuation',
    label: 'Valuation',
    domain: 'capital',
    icon: 'DollarSign',
    description: 'Run a valuation (PWERM, DCF, OPM, comps)',
    tool: 'run_valuation',
    params: [
      { key: 'method', label: 'Method', type: 'select', default: 'dcf', options: [{ label: 'DCF', value: 'dcf' }, { label: 'PWERM', value: 'pwerm' }, { label: 'OPM', value: 'opm' }, { label: 'Comparables', value: 'comps' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'dcf',
    label: 'DCF',
    domain: 'capital',
    icon: 'Calculator',
    description: 'Discounted cash flow valuation',
    tool: 'run_valuation',
    params: [
      { key: 'discount_rate', label: 'Discount Rate', type: 'percent', default: 15, min: 1, max: 50 },
      { key: 'terminal_growth', label: 'Terminal Growth', type: 'percent', default: 3, min: 0, max: 10 },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'comparables',
    label: 'Comparables',
    domain: 'capital',
    icon: 'Users',
    description: 'Comparable company analysis',
    tool: 'run_valuation',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'cap_table',
    label: 'Cap Table',
    domain: 'capital',
    icon: 'PieChart',
    description: 'Cap table evolution (Sankey visualization)',
    tool: 'cap_table_evolution',
    params: [],
    outputRenderer: 'sankey',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'liquidation_waterfall',
    label: 'Liquidation Waterfall',
    domain: 'capital',
    icon: 'Droplets',
    description: 'Liquidation waterfall analysis',
    tool: 'liquidation_waterfall',
    params: [
      { key: 'exit_value', label: 'Exit Value', type: 'currency', default: 10000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
    ],
    outputRenderer: 'waterfall',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'anti_dilution',
    label: 'Anti-Dilution',
    domain: 'capital',
    icon: 'ShieldCheck',
    description: 'Anti-dilution modeling',
    tool: 'anti_dilution_modeling',
    params: [
      { key: 'ratchet_type', label: 'Ratchet', type: 'select', default: 'broad_weighted', options: [{ label: 'Full Ratchet', value: 'full_ratchet' }, { label: 'Broad Weighted', value: 'broad_weighted' }, { label: 'Narrow Weighted', value: 'narrow_weighted' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'debt_conversion',
    label: 'Debt Conversion',
    domain: 'capital',
    icon: 'ArrowRightLeft',
    description: 'Debt conversion modeling',
    tool: 'debt_conversion_modeling',
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'funding_round',
    label: 'Funding Round',
    domain: 'capital',
    icon: 'CircleDollarSign',
    description: 'Model a funding round',
    tool: 'funding_round_model',
    kind: 'tool',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'exit_model',
    label: 'Exit Model',
    domain: 'capital',
    icon: 'LogOut',
    description: 'Model exit scenarios',
    tool: 'exit_model',
    kind: 'tool',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'round_model',
    label: 'Round Model',
    domain: 'capital',
    icon: 'Coins',
    description: 'Model round mechanics',
    tool: 'round_model',
    kind: 'tool',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
];

// ---------------------------------------------------------------------------
// Funding & Capital
// ---------------------------------------------------------------------------

const fundingChips: ChipDef[] = [
  {
    id: 'equity_raise',
    label: 'Equity Raise',
    domain: 'funding',
    icon: 'TrendingUp',
    description: 'Model an equity raise',
    tool: 'funding_injection',
    params: [
      { key: 'amount', label: 'Amount', type: 'currency', default: 5000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'dilution', label: 'Dilution', type: 'percent', default: 20 },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'debt',
    label: 'Debt',
    domain: 'funding',
    icon: 'Banknote',
    description: 'Model a debt raise',
    tool: 'funding_injection',
    params: [
      { key: 'amount', label: 'Amount', type: 'currency', default: 2000000 },
      { key: 'interest_rate', label: 'Interest', type: 'percent', default: 8 },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'safe',
    label: 'SAFE',
    domain: 'funding',
    icon: 'FileCheck',
    description: 'Model a SAFE note',
    tool: 'funding_injection',
    params: [
      { key: 'amount', label: 'Amount', type: 'currency', default: 1000000 },
      { key: 'valuation_cap', label: 'Val Cap', type: 'currency', default: 10000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M cap` },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'venture_debt',
    label: 'Venture Debt',
    domain: 'funding',
    icon: 'Landmark',
    description: 'Model venture debt',
    tool: 'advanced_debt/venture-debt',
    params: [
      { key: 'amount', label: 'Amount', type: 'currency', default: 3000000 },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
  {
    id: 'convertible',
    label: 'Convertible',
    domain: 'funding',
    icon: 'Repeat',
    description: 'Model convertible debt',
    tool: 'advanced_debt/convertible-debt',
    params: [
      { key: 'amount', label: 'Amount', type: 'currency', default: 2000000 },
      { key: 'cap', label: 'Cap', type: 'currency', default: 10000000 },
      { key: 'discount', label: 'Discount', type: 'percent', default: 20 },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// Macro Events
// ---------------------------------------------------------------------------

const macroChips: ChipDef[] = [
  {
    id: 'recession',
    label: 'Recession',
    domain: 'macro',
    icon: 'TrendingDown',
    description: 'Model a recession event',
    tool: 'analyse_macro_event',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'rate_hike',
    label: 'Rate Hike',
    domain: 'macro',
    icon: 'ArrowUpRight',
    description: 'Model an interest rate hike',
    tool: 'apply_macro_shock',
    params: [
      { key: 'basis_points', label: 'Basis Points', type: 'number', default: 100, min: 25, max: 500, step: 25, chipDisplay: (v: number) => `${v}bps` },
    ],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'market_crash',
    label: 'Market Crash',
    domain: 'macro',
    icon: 'AlertTriangle',
    description: 'Model a market crash',
    tool: 'apply_macro_shock',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'trade_war',
    label: 'Trade War',
    domain: 'macro',
    icon: 'Swords',
    description: 'Model trade war impact',
    tool: 'apply_macro_shock',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'supply_chain_shock',
    label: 'Supply Chain Shock',
    domain: 'macro',
    icon: 'Truck',
    description: 'Model supply chain disruption',
    tool: 'apply_macro_shock',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'pandemic',
    label: 'Pandemic',
    domain: 'macro',
    icon: 'Bug',
    description: 'Model pandemic impact',
    tool: 'apply_macro_shock',
    params: [
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    produces: ['macro_context'],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
];

// ---------------------------------------------------------------------------
// Company Intelligence
// ---------------------------------------------------------------------------

const intelChips: ChipDef[] = [
  {
    id: 'source_companies',
    label: 'Source Companies',
    domain: 'intel',
    icon: 'Search',
    description: 'Source companies by criteria',
    tool: 'source_companies',
    params: [
      { key: 'sector', label: 'Sector', type: 'text', default: '' },
      { key: 'stage', label: 'Stage', type: 'select', default: '', options: [{ label: 'Pre-Seed', value: 'pre-seed' }, { label: 'Seed', value: 'seed' }, { label: 'Series A', value: 'series_a' }, { label: 'Series B', value: 'series_b' }, { label: 'Growth', value: 'growth' }] },
    ],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'enrich',
    label: 'Enrich',
    domain: 'intel',
    icon: 'Sparkles',
    description: 'Enrich company data',
    tool: 'enrich_company_proactive',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'competitive_intel',
    label: 'Competitive Intel',
    domain: 'intel',
    icon: 'Target',
    description: 'Competitive intelligence analysis',
    tool: 'run_skill:competitive-intelligence',
    params: [],
    outputRenderer: 'narrative',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
  {
    id: 'market_research',
    label: 'Market Research',
    domain: 'intel',
    icon: 'BookOpen',
    description: 'Market research and sizing',
    tool: 'market_research',
    params: [
      { key: 'sector', label: 'Sector', type: 'text', default: '' },
    ],
    outputRenderer: 'narrative',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
  {
    id: 'diligence',
    label: 'Diligence',
    domain: 'intel',
    icon: 'ClipboardCheck',
    description: 'Lightweight due diligence',
    tool: 'lightweight_diligence',
    params: [],
    outputRenderer: 'narrative',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
  {
    id: 'team_comparison',
    label: 'Team Comparison',
    domain: 'intel',
    icon: 'UsersRound',
    description: 'Compare team composition',
    tool: 'team_comparison',
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
  {
    id: 'web_search',
    label: 'Web Search',
    domain: 'intel',
    icon: 'Globe',
    description: 'Search the web for intelligence',
    tool: 'web_search',
    kind: 'tool',
    params: [],
    outputRenderer: 'narrative',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
  {
    id: 'search_db',
    label: 'Search DB',
    domain: 'intel',
    icon: 'Database',
    description: 'Search the database',
    tool: 'search_database',
    kind: 'tool',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'parse_accounts',
    label: 'Parse Accounts',
    domain: 'intel',
    icon: 'FileSpreadsheet',
    description: 'Parse financial accounts',
    tool: 'parse_accounts',
    kind: 'tool',
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
  {
    id: 'build_company_list',
    label: 'Build Company List',
    domain: 'intel',
    icon: 'ListPlus',
    description: 'Build a company list from criteria',
    tool: 'build_company_list',
    kind: 'tool',
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
];

// ---------------------------------------------------------------------------
// Documents & Reporting
// ---------------------------------------------------------------------------

const reportChips: ChipDef[] = [
  {
    id: 'generate_deck',
    label: 'Generate Deck',
    domain: 'report',
    icon: 'Presentation',
    description: 'Generate a presentation deck',
    tool: 'generate_deck',
    params: [
      { key: 'template', label: 'Template', type: 'select', default: 'pitch', options: [{ label: 'Pitch Deck', value: 'pitch' }, { label: 'Board Update', value: 'board' }, { label: 'Investor Update', value: 'investor' }, { label: 'Data Room', value: 'data_room' }] },
    ],
    accepts: ['fpa', 'scenario', 'analytics', 'capital'],
    outputRenderer: 'deck',
    costTier: 'expensive',
    timeoutMs: 60000,
  },
  {
    id: 'write_memo',
    label: 'Write Memo',
    domain: 'report',
    icon: 'FileText',
    description: 'Write to investment memo',
    tool: 'write_to_memo',
    params: [
      { key: 'section', label: 'Section', type: 'text', default: '' },
    ],
    outputRenderer: 'memo-section',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
  // Old generic chart chip removed — replaced by chart domain chips
  {
    id: 'search_docs',
    label: 'Search Docs',
    domain: 'report',
    icon: 'FileSearch',
    description: 'Search across uploaded documents',
    tool: 'search_across_documents',
    params: [
      { key: 'query', label: 'Query', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'draft_contract',
    label: 'Draft Contract',
    domain: 'report',
    icon: 'FileSignature',
    description: 'Draft a legal contract',
    tool: 'draft_contract',
    params: [
      { key: 'type', label: 'Type', type: 'select', default: 'nda', options: [{ label: 'NDA', value: 'nda' }, { label: 'SHA', value: 'sha' }, { label: 'SPA', value: 'spa' }, { label: 'Term Sheet', value: 'term_sheet' }] },
    ],
    outputRenderer: 'document',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'lp_report',
    label: 'LP Report',
    domain: 'report',
    icon: 'FileBarChart',
    description: 'LP query response / reporting',
    tool: 'lp_query_response',
    params: [
      { key: 'query', label: 'Query', type: 'text', default: '' },
    ],
    outputRenderer: 'narrative',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
];

// ---------------------------------------------------------------------------
// Compliance & Legal
// ---------------------------------------------------------------------------

const complianceChips: ChipDef[] = [
  {
    id: 'kyc',
    label: 'KYC',
    domain: 'compliance',
    icon: 'UserCheck',
    description: 'KYC check',
    tool: 'kyc/check',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'aml_screen',
    label: 'AML Screen',
    domain: 'compliance',
    icon: 'ShieldAlert',
    description: 'AML screening',
    tool: 'aml/screen',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'transfer_pricing',
    label: 'Transfer Pricing',
    domain: 'compliance',
    icon: 'ArrowLeftRight',
    description: 'Transfer pricing analysis',
    tool: 'tp_analyze_transaction',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'far_analysis',
    label: 'FAR Analysis',
    domain: 'compliance',
    icon: 'BookOpenCheck',
    description: 'Functions, assets, risks analysis',
    tool: 'tp_far_analysis',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'tp_report',
    label: 'TP Report',
    domain: 'compliance',
    icon: 'FileSpreadsheet',
    description: 'Transfer pricing report generation',
    tool: 'tp_generate_report',
    params: [],
    outputRenderer: 'document',
    costTier: 'expensive',
    timeoutMs: 45000,
  },
  {
    id: 'contract_impact',
    label: 'Contract Impact',
    domain: 'compliance',
    icon: 'FileWarning',
    description: 'Contract P&L attribution',
    tool: 'contract_pnl_attribution',
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'redline_impact',
    label: 'Redline Impact',
    domain: 'compliance',
    icon: 'FileDiff',
    description: 'Redline contract impact analysis',
    tool: 'redline/redline-impact',
    params: [],
    outputRenderer: 'delta',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
];

// ---------------------------------------------------------------------------
// Portfolio Operations
// ---------------------------------------------------------------------------

const portfolioChips: ChipDef[] = [
  {
    id: 'bulk_valuation',
    label: 'Bulk Valuation',
    domain: 'portfolio',
    icon: 'Layers',
    description: 'Valuate entire portfolio',
    tool: 'bulk_valuation',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 60000,
  },
  {
    id: 'portfolio_monte_carlo',
    label: 'Portfolio Monte Carlo',
    domain: 'portfolio',
    icon: 'Dice5',
    description: 'Monte Carlo across portfolio',
    tool: 'monte_carlo_portfolio',
    params: [
      { key: 'iterations', label: 'Iterations', type: 'number', default: 10000, min: 100, max: 100000, step: 1000, chipDisplay: (v: number) => fmt(v) },
    ],
    outputRenderer: 'chart',
    costTier: 'expensive',
    timeoutMs: 60000,
  },
  {
    id: 'fund_pacing',
    label: 'Fund Pacing',
    domain: 'portfolio',
    icon: 'Timer',
    description: 'Fund pacing analysis',
    tool: 'portfolio_pacing',
    params: [],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'graduation_rates',
    label: 'Graduation Rates',
    domain: 'portfolio',
    icon: 'GraduationCap',
    description: 'Portfolio company graduation rates',
    tool: 'portfolio_graduation',
    params: [],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'fx_impact',
    label: 'FX Impact',
    domain: 'portfolio',
    icon: 'Coins',
    description: 'Foreign exchange impact on portfolio',
    tool: 'fx_portfolio_impact',
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'batch_enrich',
    label: 'Batch Enrich',
    domain: 'portfolio',
    icon: 'Sparkles',
    description: 'Batch enrich portfolio companies',
    tool: 'batch_enrich',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 60000,
  },
];

// ---------------------------------------------------------------------------
// Communications
// ---------------------------------------------------------------------------

const commsChips: ChipDef[] = [
  {
    id: 'email',
    label: 'Email',
    domain: 'comms',
    icon: 'Mail',
    description: 'Send an email',
    tool: 'send_email',
    params: [
      { key: 'recipients', label: 'To', type: 'text', default: '' },
    ],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'slack',
    label: 'Slack',
    domain: 'comms',
    icon: 'MessageSquare',
    description: 'Send a Slack message',
    tool: 'send_slack',
    params: [
      { key: 'channel', label: 'Channel', type: 'text', default: '' },
    ],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// Data & Grid
// ---------------------------------------------------------------------------

const dataChips: ChipDef[] = [
  {
    id: 'query_grid',
    label: 'Query Grid',
    domain: 'data',
    icon: 'Table2',
    description: 'Query the data grid',
    tool: 'query_grid',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'search_grid',
    label: 'Search Grid',
    domain: 'data',
    icon: 'Search',
    description: 'Search grid with conditions',
    tool: 'search_grid',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'read_financials',
    label: 'Read Financials',
    domain: 'data',
    icon: 'FileSpreadsheet',
    description: 'Read company financials',
    tool: 'read_financials',
    params: [
      { key: 'statement_type', label: 'Statement', type: 'select', default: 'income', options: [{ label: 'Income', value: 'income' }, { label: 'Balance Sheet', value: 'balance_sheet' }, { label: 'Cash Flow', value: 'cash_flow' }] },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'xero_sync',
    label: 'Xero Sync',
    domain: 'data',
    icon: 'RefreshCcw',
    description: 'Sync data from Xero',
    tool: 'fpa_xero_sync',
    params: [],
    outputRenderer: 'notification',
    costTier: 'cheap',
    timeoutMs: 30000,
  },
  {
    id: 'upload_actuals',
    label: 'Upload Actuals',
    domain: 'data',
    icon: 'Upload',
    description: 'Upload actual financial data',
    tool: 'fpa_upload_actuals',
    params: [],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 15000,
  },
  {
    id: 'ingest_docs',
    label: 'Ingest Docs',
    domain: 'data',
    icon: 'FolderInput',
    description: 'Ingest documents into the system',
    tool: 'ingest_documents',
    kind: 'tool',
    params: [],
    outputRenderer: 'notification',
    costTier: 'cheap',
    timeoutMs: 30000,
  },
  {
    id: 'bulk_write',
    label: 'Bulk Write',
    domain: 'data',
    icon: 'FileOutput',
    description: 'Bulk write to data grid',
    tool: 'bulk_write_grid',
    kind: 'tool',
    params: [],
    outputRenderer: 'notification',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'analyze_financials',
    label: 'Analyze Financials',
    domain: 'data',
    icon: 'BarChart3',
    description: 'Analyze financial statements',
    tool: 'analyze_financials',
    kind: 'tool',
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
];

// ---------------------------------------------------------------------------
// V2: Modeling Domain
// ---------------------------------------------------------------------------

const modelingChips: ChipDef[] = [
  {
    id: 'pnl_cascade',
    label: 'P&L Cascade',
    domain: 'modeling',
    icon: 'Layers',
    description: 'Full P&L cascade with department breakdowns',
    tool: 'run_cash_flow_model',
    kind: 'tool',
    params: [
      { key: 'periods', label: 'Periods', type: 'months', default: 12, min: 1, max: 60, chipDisplay: (v: number) => `${v}mo` },
      { key: 'opex_breakdown', label: 'Dept Breakdown', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No', value: 'false' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'revenue_projection',
    label: 'Revenue Projection',
    domain: 'modeling',
    icon: 'TrendingUp',
    description: 'Revenue projection with growth method',
    tool: 'revenue_projection',
    kind: 'tool',
    params: [
      { key: 'method', label: 'Method', type: 'select', default: 'growth', options: [{ label: 'Decay', value: 'decay' }, { label: 'Growth', value: 'growth' }, { label: 'S-Curve', value: 's_curve' }] },
      { key: 'periods', label: 'Periods', type: 'months', default: 12, min: 1, max: 60, chipDisplay: (v: number) => `${v}mo` },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'financial_calc',
    label: 'Financial Calculator',
    domain: 'modeling',
    icon: 'Calculator',
    description: 'NPV, IRR, PV, FV, PMT calculations',
    tool: 'financial_calculator',
    kind: 'tool',
    params: [
      { key: 'function', label: 'Function', type: 'select', default: 'npv', options: [{ label: 'NPV', value: 'npv' }, { label: 'IRR', value: 'irr' }, { label: 'PV', value: 'pv' }, { label: 'FV', value: 'fv' }] },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'run_fpa',
    label: 'Run FPA',
    domain: 'modeling',
    icon: 'Play',
    description: 'Run FPA analysis (forecast, stress, sensitivity)',
    tool: 'run_fpa',
    kind: 'tool',
    params: [
      { key: 'method', label: 'Method', type: 'select', default: 'forecast', options: [{ label: 'Forecast', value: 'forecast' }, { label: 'Stress', value: 'stress' }, { label: 'Sensitivity', value: 'sensitivity' }] },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 20000,
  },
];

// ---------------------------------------------------------------------------
// V2: Ops Domain
// ---------------------------------------------------------------------------

const opsChips: ChipDef[] = [
  {
    id: 'runway',
    label: 'Runway',
    domain: 'ops',
    icon: 'Timer',
    description: 'Calculate runway in months',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'runway_months' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'burn_rate',
    label: 'Burn Rate',
    domain: 'ops',
    icon: 'Flame',
    description: 'Calculate monthly burn rate',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'burn_rate' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'hiring_plan',
    label: 'Hiring Plan',
    domain: 'ops',
    icon: 'UserPlus',
    description: 'Generate hiring plan by department',
    tool: 'run_cash_flow_model',
    kind: 'operational',
    params: [
      { key: 'headcount_by_dept', label: 'By Dept', type: 'select', default: 'true', options: [{ label: 'Yes', value: 'true' }, { label: 'No', value: 'false' }] },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'budget_create',
    label: 'Budget Create',
    domain: 'ops',
    icon: 'FilePlus',
    description: 'Create a budget',
    tool: 'fpa_budget_create',
    kind: 'operational',
    params: [
      { key: 'name', label: 'Name', type: 'text', default: '' },
      { key: 'periods', label: 'Periods', type: 'months', default: 12, min: 1, max: 60 },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'budget_lines',
    label: 'Budget Lines',
    domain: 'ops',
    icon: 'List',
    description: 'View budget line items',
    tool: 'fpa_budget_lines',
    kind: 'operational',
    params: [
      { key: 'category', label: 'Category', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'crm_search',
    label: 'CRM Search',
    domain: 'ops',
    icon: 'Search',
    description: 'Search CRM records',
    tool: 'crm_search',
    kind: 'operational',
    params: [
      { key: 'query', label: 'Query', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'crm_log',
    label: 'CRM Log',
    domain: 'ops',
    icon: 'PenLine',
    description: 'Log a CRM interaction',
    tool: 'crm_log_interaction',
    kind: 'operational',
    params: [
      { key: 'type', label: 'Type', type: 'select', default: 'note', options: [{ label: 'Meeting', value: 'meeting' }, { label: 'Call', value: 'call' }, { label: 'Note', value: 'note' }] },
    ],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'crm_pipeline',
    label: 'CRM Pipeline',
    domain: 'ops',
    icon: 'KanbanSquare',
    description: 'Update CRM pipeline stage',
    tool: 'crm_pipeline_update',
    kind: 'operational',
    params: [
      { key: 'stage', label: 'Stage', type: 'text', default: '' },
      { key: 'deal', label: 'Deal', type: 'text', default: '' },
    ],
    outputRenderer: 'notification',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'ma_model',
    label: 'M&A Model',
    domain: 'ops',
    icon: 'Merge',
    description: 'Run M&A workflow with synergy assumptions',
    tool: 'ma_workflow',
    kind: 'tool',
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'compliance_check',
    label: 'Compliance Check',
    domain: 'ops',
    icon: 'ShieldCheck',
    description: 'Run compliance check by jurisdiction',
    tool: 'compliance_check',
    kind: 'operational',
    params: [
      { key: 'jurisdiction', label: 'Jurisdiction', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
];

// ---------------------------------------------------------------------------
// V2: Formula Chips (Operational Formulas)
// ---------------------------------------------------------------------------

const formulaChips: ChipDef[] = [
  {
    id: 'ltv_cac',
    label: 'LTV/CAC',
    domain: 'ops',
    icon: 'Ratio',
    description: 'LTV/CAC ratio',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'ltv_cac_ratio' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'rule_of_40',
    label: 'Rule of 40',
    domain: 'ops',
    icon: 'Target',
    description: 'Rule of 40 score',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'rule_of_40' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'magic_number',
    label: 'Magic Number',
    domain: 'ops',
    icon: 'Sparkles',
    description: 'SaaS magic number',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'magic_number' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'cac_payback',
    label: 'CAC Payback',
    domain: 'ops',
    icon: 'Clock',
    description: 'CAC payback period in months',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'cac_payback' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'rev_per_employee',
    label: 'Rev/Employee',
    domain: 'ops',
    icon: 'Users',
    description: 'Revenue per employee',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'revenue_per_employee' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'gross_margin',
    label: 'Gross Margin',
    domain: 'ops',
    icon: 'Percent',
    description: 'Gross margin percentage',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'gross_margin' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'net_retention',
    label: 'Net Retention',
    domain: 'ops',
    icon: 'RefreshCw',
    description: 'Net revenue retention rate',
    tool: 'fpa_computed_metrics',
    kind: 'formula',
    params: [{ key: 'metric', label: 'Metric', type: 'text', default: 'net_revenue_retention' }],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'custom_kpi',
    label: 'Custom KPI',
    domain: 'ops',
    icon: 'Sliders',
    description: 'Custom KPI from expression',
    tool: 'financial_calculator',
    kind: 'formula',
    params: [
      { key: 'expression', label: 'Expression', type: 'text', default: '' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// V2: Bridge Domain
// ---------------------------------------------------------------------------

const bridgeChips: ChipDef[] = [
  {
    id: 'contract_to_pnl',
    label: 'Contract → P&L',
    domain: 'bridge',
    icon: 'ArrowRight',
    description: 'Bridge commercial contracts to P&L line items',
    tool: 'contract_pnl_attribution',
    kind: 'bridge',
    bridgeTools: ['contract_pnl_attribution'],
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'contract_changes_to_pnl',
    label: 'Contract Changes → P&L',
    domain: 'bridge',
    icon: 'FileDiff',
    description: 'Bridge redline contract changes to financial impact',
    tool: 'model_contract_changes',
    kind: 'bridge',
    bridgeTools: ['model_contract_changes'],
    params: [],
    outputRenderer: 'delta',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'cap_table_to_val',
    label: 'Cap Table → Valuation',
    domain: 'bridge',
    icon: 'Link2',
    description: 'Bridge ownership to equity value',
    tool: 'cap_table_evolution',
    kind: 'bridge',
    bridgeTools: ['cap_table_evolution', 'run_valuation'],
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
  {
    id: 'legal_to_financial',
    label: 'Legal → Financial',
    domain: 'bridge',
    icon: 'Scale',
    description: 'Bridge legal terms to financial parameters',
    tool: 'contract_lifecycle_query',
    kind: 'bridge',
    bridgeTools: ['contract_lifecycle_query'],
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'intercompany_to_tp',
    label: 'Intercompany → TP',
    domain: 'bridge',
    icon: 'Building2',
    description: 'Bridge intercompany agreements to transfer pricing',
    tool: 'tp_analyze_transaction',
    kind: 'bridge',
    bridgeTools: ['tp_analyze_transaction'],
    params: [],
    outputRenderer: 'table',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
];

// ---------------------------------------------------------------------------
// V2: Chart Domain
// ---------------------------------------------------------------------------

const chartChips: ChipDef[] = [
  {
    id: 'line_chart',
    label: 'Line Chart',
    domain: 'chart',
    icon: 'LineChart',
    description: 'Time series & trends',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'line' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'bar_chart',
    label: 'Bar Chart',
    domain: 'chart',
    icon: 'BarChart3',
    description: 'Comparisons',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'bar' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'stacked_bar',
    label: 'Stacked Bar',
    domain: 'chart',
    icon: 'BarChart4',
    description: 'Composition over time',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'stacked_bar' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'area_chart',
    label: 'Area Chart',
    domain: 'chart',
    icon: 'AreaChart',
    description: 'Cumulative & ranges',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'area' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'waterfall_chart',
    label: 'Waterfall',
    domain: 'chart',
    icon: 'BarChart',
    description: 'P&L bridge, cash flow waterfall',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'waterfall' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'sankey_chart',
    label: 'Sankey',
    domain: 'chart',
    icon: 'GitFork',
    description: 'Ownership flow, cap table visualization',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'sankey' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'tornado_chart',
    label: 'Tornado',
    domain: 'chart',
    icon: 'ArrowUpDown',
    description: 'Sensitivity analysis tornado',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'tornado' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'heatmap_chart',
    label: 'Heatmap',
    domain: 'chart',
    icon: 'Grid3x3',
    description: 'Correlation & sensitivity matrix',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'heatmap' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'bubble_chart',
    label: 'Bubble',
    domain: 'chart',
    icon: 'Circle',
    description: '3D comparison',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'bubble' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'scatter_chart',
    label: 'Scatter',
    domain: 'chart',
    icon: 'ScatterChart',
    description: 'Correlation & clustering',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'scatter' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'treemap_chart',
    label: 'Treemap',
    domain: 'chart',
    icon: 'LayoutGrid',
    description: 'Hierarchical composition',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'treemap' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'funnel_chart',
    label: 'Funnel',
    domain: 'chart',
    icon: 'Filter',
    description: 'Pipeline & conversion',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'funnel' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'radar_chart',
    label: 'Radar',
    domain: 'chart',
    icon: 'Radar',
    description: 'Multi-metric comparison',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'radar_comparison' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'mc_histogram',
    label: 'MC Histogram',
    domain: 'chart',
    icon: 'BarChart2',
    description: 'Monte Carlo distribution histogram',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'monte_carlo_histogram' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'mc_fan',
    label: 'MC Fan',
    domain: 'chart',
    icon: 'Wind',
    description: 'Monte Carlo probability fan',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'monte_carlo_fan' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'probability_cloud',
    label: 'Prob Cloud',
    domain: 'chart',
    icon: 'Cloud',
    description: 'Exit scenario probability cloud',
    tool: 'generate_chart',
    kind: 'chart',
    params: [{ key: 'type', label: 'Type', type: 'text', default: 'probability_cloud' }],
    outputRenderer: 'chart',
    costTier: 'free',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// V2: Transform Domain
// ---------------------------------------------------------------------------

const transformChips: ChipDef[] = [
  {
    id: 'fx_convert',
    label: 'FX Convert',
    domain: 'transform',
    icon: 'ArrowLeftRight',
    description: 'Convert currency',
    tool: 'convert_currency',
    kind: 'tool',
    params: [
      { key: 'target_currency', label: 'Target', type: 'text', default: 'USD' },
    ],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 10000,
  },
  {
    id: 'fx_impact_transform',
    label: 'FX Impact',
    domain: 'transform',
    icon: 'Coins',
    description: 'FX portfolio impact analysis',
    tool: 'fx_portfolio_impact',
    kind: 'tool',
    params: [],
    outputRenderer: 'table',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'seasonality_detect',
    label: 'Seasonality Detect',
    domain: 'transform',
    icon: 'CalendarDays',
    description: 'Detect seasonal patterns in data',
    tool: 'fpa_detect_seasonality',
    kind: 'tool',
    params: [],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'seasonality_apply',
    label: 'Seasonality Apply',
    domain: 'transform',
    icon: 'CalendarCheck',
    description: 'Apply seasonal pattern to forecast',
    tool: 'fpa_apply_seasonality',
    kind: 'tool',
    params: [
      { key: 'pattern', label: 'Pattern', type: 'text', default: '' },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'correlate',
    label: 'Correlate',
    domain: 'transform',
    icon: 'Link2',
    description: 'Correlate actuals between metric pairs',
    tool: 'fpa_correlate_actuals',
    kind: 'tool',
    params: [
      { key: 'metric_a', label: 'Metric A', type: 'metric', default: 'revenue' },
      { key: 'metric_b', label: 'Metric B', type: 'metric', default: 'headcount' },
    ],
    outputRenderer: 'chart',
    costTier: 'cheap',
    timeoutMs: 10000,
  },
];

// ---------------------------------------------------------------------------
// V2: Loop Connectors
// ---------------------------------------------------------------------------

const loopChips: ChipDef[] = [
  {
    id: 'for_each_company',
    label: 'For Each Company',
    domain: 'ops',
    icon: 'Repeat',
    description: 'Iterate over portfolio companies',
    tool: '_loop',
    kind: 'loop',
    loopOver: 'companies',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'for_each_scenario',
    label: 'For Each Scenario',
    domain: 'ops',
    icon: 'Repeat',
    description: 'Iterate over scenario branches',
    tool: '_loop',
    kind: 'loop',
    loopOver: 'scenarios',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'for_each_period',
    label: 'For Each Period',
    domain: 'ops',
    icon: 'Repeat',
    description: 'Iterate over time periods',
    tool: '_loop',
    kind: 'loop',
    loopOver: 'periods',
    params: [],
    outputRenderer: 'table',
    costTier: 'free',
    timeoutMs: 5000,
  },
];

// ---------------------------------------------------------------------------
// V2: Conditional Connectors
// ---------------------------------------------------------------------------

const conditionalChips: ChipDef[] = [
  {
    id: 'if_runway_lt',
    label: 'If Runway < X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on runway threshold',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'runway_months',
    conditionOp: '<',
    params: [
      { key: 'threshold', label: 'Months', type: 'number', default: 6, min: 0, max: 36 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'if_growth_gt',
    label: 'If Growth > X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on growth rate',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'growth_rate',
    conditionOp: '>',
    params: [
      { key: 'threshold', label: 'Percent', type: 'percent', default: 25, min: 0, max: 200 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'if_valuation_gt',
    label: 'If Valuation > X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on valuation',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'valuation',
    conditionOp: '>',
    params: [
      { key: 'threshold', label: 'Value', type: 'currency', default: 10000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'if_burn_gt',
    label: 'If Burn > X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on burn rate',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'burn_rate',
    conditionOp: '>',
    params: [
      { key: 'threshold', label: 'Amount', type: 'currency', default: 500000, chipDisplay: (v: number) => `$${fmt(v / 1000)}k` },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'if_churn_gt',
    label: 'If Churn > X',
    domain: 'ops',
    icon: 'GitBranchPlus',
    description: 'Gate next step on churn rate',
    tool: '_conditional',
    kind: 'conditional',
    conditionMetric: 'churn_rate',
    conditionOp: '>',
    params: [
      { key: 'threshold', label: 'Percent', type: 'percent', default: 5, min: 0, max: 50 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
];

// ---------------------------------------------------------------------------
// V2: Assumption Connectors
// ---------------------------------------------------------------------------

const assumptionChips: ChipDef[] = [
  {
    id: 'growth_assumptions',
    label: 'Growth Assumptions',
    domain: 'driver',
    icon: 'TrendingUp',
    description: 'Bundle growth driver overrides',
    tool: '_assumption',
    kind: 'assumption',
    assumptionKeys: ['revenue_growth', 'churn_rate', 'pricing_change', 'expansion_rate'],
    params: [
      { key: 'revenue_growth', label: 'Rev Growth', type: 'percent', default: 20 },
      { key: 'churn_rate', label: 'Churn', type: 'percent', default: 5 },
      { key: 'pricing_change', label: 'Pricing Δ', type: 'percent', default: 0 },
      { key: 'expansion_rate', label: 'Expansion', type: 'percent', default: 10 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'cost_assumptions',
    label: 'Cost Assumptions',
    domain: 'driver',
    icon: 'Wallet',
    description: 'Bundle cost driver overrides',
    tool: '_assumption',
    kind: 'assumption',
    assumptionKeys: ['headcount_change', 'avg_salary', 'cogs_pct', 'opex_growth'],
    params: [
      { key: 'headcount_change', label: 'Headcount Δ', type: 'number', default: 5 },
      { key: 'avg_salary', label: 'Avg Salary', type: 'currency', default: 80000 },
      { key: 'cogs_pct', label: 'COGS %', type: 'percent', default: 35 },
      { key: 'opex_growth', label: 'Opex Growth', type: 'percent', default: 10 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'funding_assumptions',
    label: 'Funding Assumptions',
    domain: 'driver',
    icon: 'Banknote',
    description: 'Bundle funding driver overrides',
    tool: '_assumption',
    kind: 'assumption',
    assumptionKeys: ['raise_amount', 'dilution_pct', 'timeline_months', 'valuation_cap'],
    params: [
      { key: 'raise_amount', label: 'Raise', type: 'currency', default: 5000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'dilution_pct', label: 'Dilution', type: 'percent', default: 20 },
      { key: 'timeline_months', label: 'Timeline', type: 'months', default: 6 },
      { key: 'valuation_cap', label: 'Val Cap', type: 'currency', default: 20000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'macro_assumptions',
    label: 'Macro Assumptions',
    domain: 'driver',
    icon: 'Globe',
    description: 'Bundle macro driver overrides',
    tool: '_assumption',
    kind: 'assumption',
    assumptionKeys: ['interest_rate', 'inflation_rate', 'fx_rate_change', 'gdp_growth'],
    params: [
      { key: 'interest_rate', label: 'Interest', type: 'percent', default: 5 },
      { key: 'inflation_rate', label: 'Inflation', type: 'percent', default: 3 },
      { key: 'fx_rate_change', label: 'FX Δ', type: 'percent', default: 0 },
      { key: 'gdp_growth', label: 'GDP Growth', type: 'percent', default: 2 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
];

// ---------------------------------------------------------------------------
// V2: Event Connectors (Events/Priors Integration)
// ---------------------------------------------------------------------------

const eventChips: ChipDef[] = [
  {
    id: 'business_event',
    label: 'Business Event',
    domain: 'modeling',
    icon: 'Briefcase',
    description: 'Add a business event to model construction',
    tool: 'analyse_business_event',
    kind: 'event',
    eventCategory: 'business',
    params: [
      { key: 'event', label: 'Event', type: 'text', default: '' },
      { key: 'probability', label: 'Probability', type: 'percent', default: 80, min: 0, max: 100 },
      { key: 'timing', label: 'Timing', type: 'text', default: '' },
    ],
    outputRenderer: 'raw',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'macro_event',
    label: 'Macro Event',
    domain: 'modeling',
    icon: 'Globe',
    description: 'Add a macro event to model construction',
    tool: 'analyse_macro_event',
    kind: 'event',
    eventCategory: 'macro',
    params: [
      { key: 'event', label: 'Event', type: 'text', default: '' },
      { key: 'probability', label: 'Probability', type: 'percent', default: 60, min: 0, max: 100 },
      { key: 'severity', label: 'Severity', type: 'select', default: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Severe', value: 'severe' }] },
    ],
    outputRenderer: 'raw',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'funding_event',
    label: 'Funding Event',
    domain: 'modeling',
    icon: 'Banknote',
    description: 'Add a funding event to model construction',
    tool: '_funding_event',
    kind: 'event',
    eventCategory: 'funding',
    params: [
      { key: 'type', label: 'Type', type: 'select', default: 'equity', options: [{ label: 'Equity', value: 'equity' }, { label: 'Debt', value: 'debt' }, { label: 'SAFE', value: 'safe' }] },
      { key: 'amount', label: 'Amount', type: 'currency', default: 5000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'period', label: 'Period', type: 'months', default: 3 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'operational_event',
    label: 'Ops Event',
    domain: 'modeling',
    icon: 'Settings',
    description: 'Add an operational event to model construction',
    tool: 'analyse_business_event',
    kind: 'event',
    eventCategory: 'operational',
    params: [
      { key: 'event', label: 'Event', type: 'text', default: '' },
      { key: 'probability', label: 'Probability', type: 'percent', default: 80, min: 0, max: 100 },
    ],
    outputRenderer: 'raw',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'market_event',
    label: 'Market Event',
    domain: 'modeling',
    icon: 'TrendingDown',
    description: 'Add a market event to model construction',
    tool: 'analyse_macro_event',
    kind: 'event',
    eventCategory: 'market',
    params: [
      { key: 'event', label: 'Event', type: 'text', default: '' },
      { key: 'probability', label: 'Probability', type: 'percent', default: 50, min: 0, max: 100 },
    ],
    outputRenderer: 'raw',
    costTier: 'cheap',
    timeoutMs: 15000,
  },
  {
    id: 'add_event_chain',
    label: 'Event Chain',
    domain: 'modeling',
    icon: 'Link',
    description: 'Build full event chain from NL description',
    tool: 'construct_forecast_model',
    kind: 'event',
    params: [
      { key: 'prompt', label: 'Description', type: 'text', default: '' },
    ],
    outputRenderer: 'raw',
    costTier: 'expensive',
    timeoutMs: 30000,
  },
];

// ---------------------------------------------------------------------------
// V2: Prior Connectors (Events/Priors Integration)
// ---------------------------------------------------------------------------

const priorChips: ChipDef[] = [
  {
    id: 'set_confidence',
    label: 'Set Confidence',
    domain: 'modeling',
    icon: 'Gauge',
    description: 'Set confidence level on downstream curves',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['confidence'],
    params: [
      { key: 'confidence', label: 'Confidence', type: 'percent', default: 80, min: 0, max: 100 },
      { key: 'distribution', label: 'Distribution', type: 'select', default: 'normal', options: [{ label: 'Normal', value: 'normal' }, { label: 'Beta', value: 'beta' }, { label: 'Triangular', value: 'triangular' }] },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'set_ceiling',
    label: 'Set Ceiling',
    domain: 'modeling',
    icon: 'ArrowUpToLine',
    description: 'Set ceiling on a curve metric',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['ceiling'],
    params: [
      { key: 'ceiling', label: 'Ceiling', type: 'currency', default: 10000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
      { key: 'metric', label: 'Metric', type: 'metric', default: 'revenue' },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'set_floor',
    label: 'Set Floor',
    domain: 'modeling',
    icon: 'ArrowDownToLine',
    description: 'Set floor on a curve metric',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['floor'],
    params: [
      { key: 'floor', label: 'Floor', type: 'currency', default: 0 },
      { key: 'metric', label: 'Metric', type: 'metric', default: 'revenue' },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'growth_prior',
    label: 'Growth Prior',
    domain: 'modeling',
    icon: 'TrendingUp',
    description: 'Set confidence and ceiling on revenue curve',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['revenue.confidence', 'revenue.ceiling'],
    params: [
      { key: 'confidence', label: 'Confidence', type: 'percent', default: 90, min: 0, max: 100 },
      { key: 'ceiling', label: 'Ceiling', type: 'currency', default: 2000000, chipDisplay: (v: number) => `$${fmt(v / 1000000)}M` },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
  {
    id: 'cost_prior',
    label: 'Cost Prior',
    domain: 'modeling',
    icon: 'Wallet',
    description: 'Set confidence on cost curves',
    tool: '_prior',
    kind: 'prior',
    priorKeys: ['opex.confidence', 'cogs.confidence'],
    params: [
      { key: 'confidence', label: 'Confidence', type: 'percent', default: 70, min: 0, max: 100 },
    ],
    outputRenderer: 'raw',
    costTier: 'free',
    timeoutMs: 5000,
  },
];

// ---------------------------------------------------------------------------
// Combined Registry
// ---------------------------------------------------------------------------

export const CHIP_REGISTRY: ChipDef[] = [
  ...fpaChips,
  ...scenarioChips,
  ...analyticsChips,
  ...capitalChips,
  ...fundingChips,
  ...macroChips,
  ...intelChips,
  ...reportChips,
  ...complianceChips,
  ...portfolioChips,
  ...commsChips,
  ...dataChips,
  // V2 domains:
  ...modelingChips,
  ...opsChips,
  ...formulaChips,
  ...bridgeChips,
  ...chartChips,
  ...transformChips,
  // V2 connectors:
  ...loopChips,
  ...conditionalChips,
  ...assumptionChips,
  ...eventChips,
  ...priorChips,
];

/** Lookup by chip ID */
export const CHIP_BY_ID: Record<string, ChipDef> = Object.fromEntries(
  CHIP_REGISTRY.map((c) => [c.id, c]),
);

/** Group chips by domain */
export function chipsByDomain(): Record<string, ChipDef[]> {
  const grouped: Record<string, ChipDef[]> = {};
  for (const chip of CHIP_REGISTRY) {
    (grouped[chip.domain] ??= []).push(chip);
  }
  return grouped;
}

/** Search chips by label/description */
export function searchChips(query: string): ChipDef[] {
  const q = query.toLowerCase().trim();
  if (!q) return CHIP_REGISTRY;
  return CHIP_REGISTRY.filter(
    (c) =>
      c.label.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.domain.includes(q) ||
      c.tool.toLowerCase().includes(q),
  );
}
