"""Workday OAuth 2.0 authentication.

Implements the Workday OAuth2 refresh-token flow:
1. Admin registers an API Client for Integrations in Workday
2. Admin generates a refresh token in the Workday UI
3. We use the refresh token to obtain short-lived access tokens (~60 min)
4. Refresh tokens are long-lived (typically 1 year, configured by admin)

Token endpoint: https://<host>/ccx/oauth2/<tenant>/token
Grant type:     refresh_token (Workday does NOT support client_credentials
                for data APIs)

There is no user-facing authorize URL -- the refresh token is generated by
the Workday admin directly in the UI, so no ``build_auth_url`` is needed.
"""

import logging
from typing import Any, Dict

import httpx

logger = logging.getLogger(__name__)


def _token_url(host: str, tenant: str) -> str:
    """Build the Workday OAuth2 token endpoint URL."""
    return f"https://{host}/ccx/oauth2/{tenant}/token"


async def refresh_access_token(
    refresh_token: str,
    client_id: str,
    client_secret: str,
    host: str,
    tenant: str,
) -> Dict[str, Any]:
    """Refresh a Workday access token.

    POST https://<host>/ccx/oauth2/<tenant>/token
      grant_type=refresh_token
      refresh_token=<refresh_token>
      client_id=<client_id>
      client_secret=<client_secret>

    Returns:
        {success, access_token, refresh_token (may rotate), expires_in}
    """
    url = _token_url(host, tenant)

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(
                url,
                headers={
                    "Accept": "application/json",
                    "Content-Type": "application/x-www-form-urlencoded",
                },
                data={
                    "grant_type": "refresh_token",
                    "refresh_token": refresh_token,
                    "client_id": client_id,
                    "client_secret": client_secret,
                },
            )

        if response.status_code != 200:
            logger.error(
                "Workday token refresh failed: %d %s",
                response.status_code,
                response.text[:500],
            )
            return {
                "success": False,
                "error": f"HTTP {response.status_code}: {response.text[:200]}",
            }

        data = response.json()
        return {
            "success": True,
            "access_token": data["access_token"],
            "refresh_token": data.get("refresh_token", refresh_token),
            "expires_in": data.get("expires_in", 3600),
        }
    except httpx.TimeoutException:
        logger.error("Workday token refresh timed out (host=%s, tenant=%s)", host, tenant)
        return {"success": False, "error": "Request timed out"}
    except Exception as e:
        logger.error("Workday token refresh error: %s", e)
        return {"success": False, "error": str(e)}


async def validate_connection(
    access_token: str,
    host: str,
    tenant: str,
) -> Dict[str, Any]:
    """Validate a Workday connection by fetching worker count.

    GET https://<host>/ccx/api/v1/<tenant>/workers?limit=1

    A successful 200 response confirms the access token and tenant
    are valid and the API Client has the required permissions.

    Returns:
        {success: bool, error: str?}
    """
    url = f"https://{host}/ccx/api/v1/{tenant}/workers"

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.get(
                url,
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Accept": "application/json",
                },
                params={"limit": 1},
            )

        if response.status_code == 401:
            logger.error("Workday validation failed: 401 Unauthorized")
            return {
                "success": False,
                "error": "Invalid or expired access token",
            }

        if response.status_code == 403:
            logger.error("Workday validation failed: 403 Forbidden")
            return {
                "success": False,
                "error": "API Client does not have sufficient permissions",
            }

        if response.status_code != 200:
            logger.error(
                "Workday validation failed: %d %s",
                response.status_code,
                response.text[:500],
            )
            return {
                "success": False,
                "error": f"HTTP {response.status_code}: {response.text[:200]}",
            }

        logger.info(
            "Workday connection validated (host=%s, tenant=%s)",
            host,
            tenant,
        )
        return {"success": True}

    except httpx.TimeoutException:
        logger.error("Workday validation timed out (host=%s, tenant=%s)", host, tenant)
        return {"success": False, "error": "Request timed out"}
    except Exception as e:
        logger.error("Workday validation error: %s", e)
        return {"success": False, "error": str(e)}
