-- Create table for storing company CIMs generated by the agent
CREATE TABLE IF NOT EXISTS company_cims (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_name TEXT NOT NULL,
  website_url TEXT,
  cim_data JSONB NOT NULL,
  data_quality_score INTEGER,
  sources_count INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_company_cims_name ON company_cims(company_name);
CREATE INDEX IF NOT EXISTS idx_company_cims_created ON company_cims(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_company_cims_quality ON company_cims(data_quality_score DESC);

-- Create unique constraint on company name to prevent duplicates
CREATE UNIQUE INDEX IF NOT EXISTS idx_company_cims_unique_name ON company_cims(LOWER(company_name));

-- Add RLS policies if needed
ALTER TABLE company_cims ENABLE ROW LEVEL SECURITY;

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_company_cims_updated_at
  BEFORE UPDATE ON company_cims
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();